// GENERATED by types/gen-imgui-dts.py - do not edit by hand.
//
// Types for the "ImGui" module registered by src/Script.cpp
// (imgui-quickjs/imgui-quickjs.cpp). The same object is passed
// to the entry module's draw_gui export.
//
// These wrappers are NOT the C++ ImGui API: there are no output
// pointers, so a widget returns its new state - `const r =
// ImGui.SliderFloat(...); if (r.changed) x = r.value;` - and the
// optional trailing arguments are an options object rather than
// positional parameters.

declare module "ImGui" {
  /** An ImVec2, as {x, y}. */
  export interface Vec2 {
    x: number;
    y: number;
  }

  /** An ImVec4 / ImColor, as {x, y, z, w}. */
  export interface Vec4 {
    x: number;
    y: number;
    z: number;
    w: number;
  }

  // --- Enums -------------------------------------------------------

  export const WindowFlags: {
    readonly None: number;
    readonly NoTitleBar: number;
    readonly NoResize: number;
    readonly NoMove: number;
    readonly NoScrollbar: number;
    readonly NoScrollWithMouse: number;
    readonly NoCollapse: number;
    readonly AlwaysAutoResize: number;
    readonly NoBackground: number;
    readonly NoSavedSettings: number;
    readonly NoMouseInputs: number;
    readonly MenuBar: number;
    readonly HorizontalScrollbar: number;
    readonly NoFocusOnAppearing: number;
    readonly NoBringToFrontOnFocus: number;
    readonly AlwaysVerticalScrollbar: number;
    readonly AlwaysHorizontalScrollbar: number;
    readonly NoNavInputs: number;
    readonly NoNavFocus: number;
    readonly UnsavedDocument: number;
    readonly NoNav: number;
    readonly NoDecoration: number;
    readonly NoInputs: number;
  };
  export const ChildFlags: {
    readonly None: number;
    readonly Borders: number;
    readonly AlwaysUseWindowPadding: number;
    readonly ResizeX: number;
    readonly ResizeY: number;
    readonly AutoResizeX: number;
    readonly AutoResizeY: number;
    readonly AlwaysAutoResize: number;
    readonly FrameStyle: number;
    readonly NavFlattened: number;
  };
  export const ItemFlags: {
    readonly None: number;
    readonly NoTabStop: number;
    readonly NoNav: number;
    readonly NoNavDefaultFocus: number;
    readonly ButtonRepeat: number;
    readonly AutoClosePopups: number;
    readonly AllowDuplicateId: number;
  };
  export const InputTextFlags: {
    readonly None: number;
    readonly CharsDecimal: number;
    readonly CharsHexadecimal: number;
    readonly CharsScientific: number;
    readonly CharsUppercase: number;
    readonly CharsNoBlank: number;
    readonly AllowTabInput: number;
    readonly EnterReturnsTrue: number;
    readonly EscapeClearsAll: number;
    readonly CtrlEnterForNewLine: number;
    readonly ReadOnly: number;
    readonly AlwaysOverwrite: number;
    readonly AutoSelectAll: number;
    readonly ParseEmptyRefVal: number;
    readonly DisplayEmptyRefVal: number;
    readonly NoHorizontalScroll: number;
    readonly NoUndoRedo: number;
    readonly ElideLeft: number;
    readonly CallbackCompletion: number;
    readonly CallbackHistory: number;
    readonly CallbackAlways: number;
    readonly CallbackCharFilter: number;
    readonly CallbackResize: number;
    readonly CallbackEdit: number;
  };
  export const SliderFlags: {
    readonly None: number;
    readonly Logarithmic: number;
    readonly NoRoundToFormat: number;
    readonly NoInput: number;
    readonly WrapAround: number;
    readonly ClampOnInput: number;
    readonly ClampZeroRange: number;
    readonly AlwaysClamp: number;
  };
  export const TreeNodeFlags: {
    readonly None: number;
    readonly Selected: number;
    readonly Framed: number;
    readonly AllowOverlap: number;
    readonly NoTreePushOnOpen: number;
    readonly NoAutoOpenOnLog: number;
    readonly DefaultOpen: number;
    readonly OpenOnDoubleClick: number;
    readonly OpenOnArrow: number;
    readonly Leaf: number;
    readonly Bullet: number;
    readonly FramePadding: number;
    readonly SpanAvailWidth: number;
    readonly SpanFullWidth: number;
    readonly SpanLabelWidth: number;
    readonly SpanAllColumns: number;
    readonly LabelSpanAllColumns: number;
    readonly NavLeftJumpsBackHere: number;
    readonly CollapsingHeader: number;
  };
  export const PopupFlags: {
    readonly None: number;
    readonly MouseButtonLeft: number;
    readonly MouseButtonRight: number;
    readonly MouseButtonMiddle: number;
    readonly MouseButtonMask_: number;
    readonly NoReopen: number;
    readonly NoOpenOverExistingPopup: number;
    readonly NoOpenOverItems: number;
    readonly AnyPopupId: number;
    readonly AnyPopupLevel: number;
    readonly AnyPopup: number;
  };
  export const SelectableFlags: {
    readonly None: number;
    readonly NoAutoClosePopups: number;
    readonly SpanAllColumns: number;
    readonly AllowDoubleClick: number;
    readonly Disabled: number;
    readonly AllowOverlap: number;
    readonly Highlight: number;
  };
  export const ComboFlags: {
    readonly None: number;
    readonly PopupAlignLeft: number;
    readonly HeightSmall: number;
    readonly HeightRegular: number;
    readonly HeightLarge: number;
    readonly HeightLargest: number;
    readonly NoArrowButton: number;
    readonly NoPreview: number;
    readonly WidthFitPreview: number;
    readonly HeightMask_: number;
  };
  export const TabBarFlags: {
    readonly None: number;
    readonly Reorderable: number;
    readonly AutoSelectNewTabs: number;
    readonly TabListPopupButton: number;
    readonly NoCloseWithMiddleMouseButton: number;
    readonly NoTabListScrollingButtons: number;
    readonly NoTooltip: number;
    readonly DrawSelectedOverline: number;
    readonly FittingPolicyResizeDown: number;
    readonly FittingPolicyScroll: number;
    readonly FittingPolicyMask_: number;
    readonly FittingPolicyDefault_: number;
  };
  export const TabItemFlags: {
    readonly None: number;
    readonly UnsavedDocument: number;
    readonly SetSelected: number;
    readonly NoCloseWithMiddleMouseButton: number;
    readonly NoPushId: number;
    readonly NoTooltip: number;
    readonly NoReorder: number;
    readonly Leading: number;
    readonly Trailing: number;
    readonly NoAssumedClosure: number;
  };
  export const FocusedFlags: {
    readonly None: number;
    readonly ChildWindows: number;
    readonly RootWindow: number;
    readonly AnyWindow: number;
    readonly NoPopupHierarchy: number;
    readonly RootAndChildWindows: number;
  };
  export const HoveredFlags: {
    readonly None: number;
    readonly ChildWindows: number;
    readonly RootWindow: number;
    readonly AnyWindow: number;
    readonly NoPopupHierarchy: number;
    readonly AllowWhenBlockedByPopup: number;
    readonly AllowWhenBlockedByActiveItem: number;
    readonly AllowWhenOverlappedByItem: number;
    readonly AllowWhenOverlappedByWindow: number;
    readonly AllowWhenDisabled: number;
    readonly NoNavOverride: number;
    readonly AllowWhenOverlapped: number;
    readonly RectOnly: number;
    readonly RootAndChildWindows: number;
    readonly ForTooltip: number;
    readonly Stationary: number;
    readonly DelayNone: number;
    readonly DelayShort: number;
    readonly DelayNormal: number;
    readonly NoSharedDelay: number;
  };
  export const DragDropFlags: {
    readonly None: number;
    readonly SourceNoPreviewTooltip: number;
    readonly SourceNoDisableHover: number;
    readonly SourceNoHoldToOpenOthers: number;
    readonly SourceAllowNullID: number;
    readonly SourceExtern: number;
    readonly PayloadAutoExpire: number;
    readonly PayloadNoCrossContext: number;
    readonly PayloadNoCrossProcess: number;
    readonly AcceptBeforeDelivery: number;
    readonly AcceptNoDrawDefaultRect: number;
    readonly AcceptNoPreviewTooltip: number;
    readonly AcceptPeekOnly: number;
  };
  export const Dir: {
    readonly None: number;
    readonly Left: number;
    readonly Right: number;
    readonly Up: number;
    readonly Down: number;
  };
  export const SortDirection: {
    readonly None: number;
    readonly Ascending: number;
    readonly Descending: number;
  };
  export const Key: {
    readonly None: number;
    readonly Tab: number;
    readonly LeftArrow: number;
    readonly RightArrow: number;
    readonly UpArrow: number;
    readonly DownArrow: number;
    readonly PageUp: number;
    readonly PageDown: number;
    readonly Home: number;
    readonly End: number;
    readonly Insert: number;
    readonly Delete: number;
    readonly Backspace: number;
    readonly Space: number;
    readonly Enter: number;
    readonly Escape: number;
    readonly LeftCtrl: number;
    readonly LeftShift: number;
    readonly LeftAlt: number;
    readonly LeftSuper: number;
    readonly RightCtrl: number;
    readonly RightShift: number;
    readonly RightAlt: number;
    readonly RightSuper: number;
    readonly Menu: number;
    readonly 0: number;
    readonly 1: number;
    readonly 2: number;
    readonly 3: number;
    readonly 4: number;
    readonly 5: number;
    readonly 6: number;
    readonly 7: number;
    readonly 8: number;
    readonly 9: number;
    readonly A: number;
    readonly B: number;
    readonly C: number;
    readonly D: number;
    readonly E: number;
    readonly F: number;
    readonly G: number;
    readonly H: number;
    readonly I: number;
    readonly J: number;
    readonly K: number;
    readonly L: number;
    readonly M: number;
    readonly N: number;
    readonly O: number;
    readonly P: number;
    readonly Q: number;
    readonly R: number;
    readonly S: number;
    readonly T: number;
    readonly U: number;
    readonly V: number;
    readonly W: number;
    readonly X: number;
    readonly Y: number;
    readonly Z: number;
    readonly F1: number;
    readonly F2: number;
    readonly F3: number;
    readonly F4: number;
    readonly F5: number;
    readonly F6: number;
    readonly F7: number;
    readonly F8: number;
    readonly F9: number;
    readonly F10: number;
    readonly F11: number;
    readonly F12: number;
    readonly F13: number;
    readonly F14: number;
    readonly F15: number;
    readonly F16: number;
    readonly F17: number;
    readonly F18: number;
    readonly F19: number;
    readonly F20: number;
    readonly F21: number;
    readonly F22: number;
    readonly F23: number;
    readonly F24: number;
    readonly Apostrophe: number;
    readonly Comma: number;
    readonly Minus: number;
    readonly Period: number;
    readonly Slash: number;
    readonly Semicolon: number;
    readonly Equal: number;
    readonly LeftBracket: number;
    readonly Backslash: number;
    readonly RightBracket: number;
    readonly GraveAccent: number;
    readonly CapsLock: number;
    readonly ScrollLock: number;
    readonly NumLock: number;
    readonly PrintScreen: number;
    readonly Pause: number;
    readonly Keypad0: number;
    readonly Keypad1: number;
    readonly Keypad2: number;
    readonly Keypad3: number;
    readonly Keypad4: number;
    readonly Keypad5: number;
    readonly Keypad6: number;
    readonly Keypad7: number;
    readonly Keypad8: number;
    readonly Keypad9: number;
    readonly KeypadDecimal: number;
    readonly KeypadDivide: number;
    readonly KeypadMultiply: number;
    readonly KeypadSubtract: number;
    readonly KeypadAdd: number;
    readonly KeypadEnter: number;
    readonly KeypadEqual: number;
    readonly AppBack: number;
    readonly AppForward: number;
    readonly Oem102: number;
    readonly GamepadStart: number;
    readonly GamepadBack: number;
    readonly GamepadFaceLeft: number;
    readonly GamepadFaceRight: number;
    readonly GamepadFaceUp: number;
    readonly GamepadFaceDown: number;
    readonly GamepadDpadLeft: number;
    readonly GamepadDpadRight: number;
    readonly GamepadDpadUp: number;
    readonly GamepadDpadDown: number;
    readonly GamepadL1: number;
    readonly GamepadR1: number;
    readonly GamepadL2: number;
    readonly GamepadR2: number;
    readonly GamepadL3: number;
    readonly GamepadR3: number;
    readonly GamepadLStickLeft: number;
    readonly GamepadLStickRight: number;
    readonly GamepadLStickUp: number;
    readonly GamepadLStickDown: number;
    readonly GamepadRStickLeft: number;
    readonly GamepadRStickRight: number;
    readonly GamepadRStickUp: number;
    readonly GamepadRStickDown: number;
    readonly MouseLeft: number;
    readonly MouseRight: number;
    readonly MouseMiddle: number;
    readonly MouseX1: number;
    readonly MouseX2: number;
    readonly MouseWheelX: number;
    readonly MouseWheelY: number;
  };
  export const Mod: {
    readonly None: number;
    readonly Ctrl: number;
    readonly Shift: number;
    readonly Alt: number;
    readonly Super: number;
    readonly Mask_: number;
  };
  export const MouseButton: {
    readonly Left: number;
    readonly Right: number;
    readonly Middle: number;
  };
  export const InputFlags: {
    readonly None: number;
    readonly Repeat: number;
    readonly RouteActive: number;
    readonly RouteFocused: number;
    readonly RouteGlobal: number;
    readonly RouteAlways: number;
    readonly RouteOverFocused: number;
    readonly RouteOverActive: number;
    readonly RouteUnlessBgFocused: number;
    readonly RouteFromRootWindow: number;
    readonly Tooltip: number;
  };
  export const ConfigFlags: {
    readonly None: number;
    readonly NavEnableKeyboard: number;
    readonly NavEnableGamepad: number;
    readonly NoMouse: number;
    readonly NoMouseCursorChange: number;
    readonly NoKeyboard: number;
    readonly IsSRGB: number;
    readonly IsTouchScreen: number;
  };
  export const Col: {
    readonly Text: number;
    readonly TextDisabled: number;
    readonly WindowBg: number;
    readonly ChildBg: number;
    readonly PopupBg: number;
    readonly Border: number;
    readonly BorderShadow: number;
    readonly FrameBg: number;
    readonly FrameBgHovered: number;
    readonly FrameBgActive: number;
    readonly TitleBg: number;
    readonly TitleBgActive: number;
    readonly TitleBgCollapsed: number;
    readonly MenuBarBg: number;
    readonly ScrollbarBg: number;
    readonly ScrollbarGrab: number;
    readonly ScrollbarGrabHovered: number;
    readonly ScrollbarGrabActive: number;
    readonly CheckMark: number;
    readonly SliderGrab: number;
    readonly SliderGrabActive: number;
    readonly Button: number;
    readonly ButtonHovered: number;
    readonly ButtonActive: number;
    readonly Header: number;
    readonly HeaderHovered: number;
    readonly HeaderActive: number;
    readonly Separator: number;
    readonly SeparatorHovered: number;
    readonly SeparatorActive: number;
    readonly ResizeGrip: number;
    readonly ResizeGripHovered: number;
    readonly ResizeGripActive: number;
    readonly TabHovered: number;
    readonly Tab: number;
    readonly TabSelected: number;
    readonly TabSelectedOverline: number;
    readonly TabDimmed: number;
    readonly TabDimmedSelected: number;
    readonly TabDimmedSelectedOverline: number;
    readonly PlotLines: number;
    readonly PlotLinesHovered: number;
    readonly PlotHistogram: number;
    readonly PlotHistogramHovered: number;
    readonly TableHeaderBg: number;
    readonly TableBorderStrong: number;
    readonly TableBorderLight: number;
    readonly TableRowBg: number;
    readonly TableRowBgAlt: number;
    readonly TextLink: number;
    readonly TextSelectedBg: number;
    readonly DragDropTarget: number;
    readonly NavCursor: number;
    readonly NavWindowingHighlight: number;
    readonly NavWindowingDimBg: number;
    readonly ModalWindowDimBg: number;
  };
  export const ButtonFlags: {
    readonly None: number;
    readonly MouseButtonLeft: number;
    readonly MouseButtonRight: number;
    readonly MouseButtonMiddle: number;
  };
  export const ColorEditFlags: {
    readonly None: number;
    readonly NoAlpha: number;
    readonly NoPicker: number;
    readonly NoOptions: number;
    readonly NoSmallPreview: number;
    readonly NoInputs: number;
    readonly NoTooltip: number;
    readonly NoLabel: number;
    readonly NoSidePreview: number;
    readonly NoDragDrop: number;
    readonly NoBorder: number;
    readonly AlphaOpaque: number;
    readonly AlphaNoBg: number;
    readonly AlphaPreviewHalf: number;
    readonly AlphaBar: number;
    readonly HDR: number;
    readonly DisplayRGB: number;
    readonly DisplayHSV: number;
    readonly DisplayHex: number;
    readonly Uint8: number;
    readonly Float: number;
    readonly PickerHueBar: number;
    readonly PickerHueWheel: number;
    readonly InputRGB: number;
    readonly InputHSV: number;
    readonly DefaultOptions_: number;
  };
  export const TableFlags: {
    readonly None: number;
    readonly Resizable: number;
    readonly Reorderable: number;
    readonly Hideable: number;
    readonly Sortable: number;
    readonly NoSavedSettings: number;
    readonly ContextMenuInBody: number;
    readonly RowBg: number;
    readonly BordersInnerH: number;
    readonly BordersOuterH: number;
    readonly BordersInnerV: number;
    readonly BordersOuterV: number;
    readonly BordersH: number;
    readonly BordersV: number;
    readonly BordersInner: number;
    readonly BordersOuter: number;
    readonly Borders: number;
    readonly NoBordersInBody: number;
    readonly NoBordersInBodyUntilResize: number;
    readonly SizingFixedFit: number;
    readonly SizingFixedSame: number;
    readonly SizingStretchProp: number;
    readonly SizingStretchSame: number;
    readonly NoHostExtendX: number;
    readonly NoHostExtendY: number;
    readonly NoKeepColumnsVisible: number;
    readonly PreciseWidths: number;
    readonly NoClip: number;
    readonly PadOuterX: number;
    readonly NoPadOuterX: number;
    readonly NoPadInnerX: number;
    readonly ScrollX: number;
    readonly ScrollY: number;
    readonly SortMulti: number;
    readonly SortTristate: number;
    readonly HighlightHoveredColumn: number;
  };
  export const TableColumnFlags: {
    readonly None: number;
    readonly Disabled: number;
    readonly DefaultHide: number;
    readonly DefaultSort: number;
    readonly WidthStretch: number;
    readonly WidthFixed: number;
    readonly NoResize: number;
    readonly NoReorder: number;
    readonly NoHide: number;
    readonly NoClip: number;
    readonly NoSort: number;
    readonly NoSortAscending: number;
    readonly NoSortDescending: number;
    readonly NoHeaderLabel: number;
    readonly NoHeaderWidth: number;
    readonly PreferSortAscending: number;
    readonly PreferSortDescending: number;
    readonly IndentEnable: number;
    readonly IndentDisable: number;
    readonly AngledHeader: number;
    readonly IsEnabled: number;
    readonly IsVisible: number;
    readonly IsSorted: number;
    readonly IsHovered: number;
  };
  export const TableRowFlags: {
    readonly None: number;
    readonly Headers: number;
  };
  export const TableBgTarget: {
    readonly None: number;
    readonly RowBg0: number;
    readonly RowBg1: number;
    readonly CellBg: number;
  };

  // --- Text Widgets ------------------------------------------------

  /** ImGui::Text(const char* text) */
  export function Text(text: string): void;
  /** ImGui::TextColored(const ImVec4& col, const char* text) */
  export function TextColored(col: Vec4, text: string): void;
  /** ImGui::TextDisabled(const char* text) */
  export function TextDisabled(text: string): void;
  /** ImGui::TextWrapped(const char* text) */
  export function TextWrapped(text: string): void;
  /** ImGui::LabelText(const char* label, const char* text) */
  export function LabelText(label: string, text: string): void;
  /** ImGui::BulletText(const char* text) */
  export function BulletText(text: string): void;
  /** ImGui::SeparatorText(const char* label) */
  export function SeparatorText(label: string): void;

  // --- Button Widgets ----------------------------------------------

  /** ImGui::Button(const char* label, const ImVec2& size = ImVec2(0,0)) */
  export function Button(label: string, options?: { size?: Vec2 }): boolean;
  /** ImGui::SmallButton(const char* label) */
  export function SmallButton(label: string): boolean;
  /** ImGui::InvisibleButton(const char* str_id, const ImVec2& size, */
  export function InvisibleButton(str_id: string, size: Vec2, options?: { flags?: number }): boolean;
  /** ImGui::ArrowButton(const char* str_id, ImGuiDir dir) */
  export function ArrowButton(str_id: string, dir: number): boolean;
  /** ImGui::Checkbox(const char* label, bool* v) */
  export function Checkbox(label: string, v: boolean): { changed: boolean; value: boolean };
  /** ImGui::RadioButton(const char* label, bool active) */
  export function RadioButton(label: string, active: boolean): boolean;
  /** ImGui::RadioButton(const char* label, int* v, int v_button) */
  export function RadioButtonEx(label: string, value: number, v_button: number): { changed: boolean; value: number };

  // --- Other Basic Widgets -----------------------------------------

  /** ImGui::ProgressBar(float fraction, const ImVec2& size_arg = */
  export function ProgressBar(fraction: number, options?: { size?: Vec2; overlay?: string }): void;
  /** ImGui::Bullet() */
  export function Bullet(): void;
  /** ImGui::Image(ImTextureID user_texture_id, const ImVec2& image_size, ...) */
  export function Image(texture_id: number, image_size: Vec2, options?: { uv0?: Vec2; uv1?: Vec2; tint_col?: Vec4; border_col?: Vec4 }): void;
  /** ImGui::ImageButton(const char* str_id, ImTextureID user_texture_id, const */
  export function ImageButton(str_id: string, texture_id: number, image_size: Vec2, options?: { uv0?: Vec2; uv1?: Vec2; bg_col?: Vec4; tint_col?: Vec4 }): boolean;

  // --- Input Text Widgets ------------------------------------------

  /** ImGui::InputText(const char* label, char* buf, size_t buf_size, */
  export function InputText(label: string, text: string, options?: { flags?: number }): { changed: boolean; text: string };
  /** ImGui::InputTextMultiline(const char* label, char* buf, size_t buf_size, */
  export function InputTextMultiline(label: string, text: string, options?: { size?: Vec2; flags?: number }): { changed: boolean; text: string };
  /** ImGui::InputTextWithHint(const char* label, const char* hint, char* buf, */
  export function InputTextWithHint(label: string, hint: string, text: string, options?: { flags?: number }): { changed: boolean; text: string };

  // --- Input Number Widgets ----------------------------------------

  /** ImGui::InputFloat(const char* label, float* v, float step = 0.0f, float */
  export function InputFloat(label: string, value: number, options?: { step?: number; stepFast?: number; format?: string; flags?: number }): { changed: boolean; value: number };
  /** ImGui::InputFloat2(const char* label, float v[2], const char* format = */
  export function InputFloat2(label: string, values: number[], options?: { format?: string; flags?: number }): { changed: boolean; values: number[] };
  /** ImGui::InputFloat3(const char* label, float v[3], const char* format = */
  export function InputFloat3(label: string, values: number[], options?: { format?: string; flags?: number }): { changed: boolean; values: number[] };
  /** ImGui::InputFloat4(const char* label, float v[4], const char* format = */
  export function InputFloat4(label: string, values: number[], options?: { format?: string; flags?: number }): { changed: boolean; values: number[] };
  /** ImGui::InputInt(const char* label, int* v, int step = 1, int step_fast = 100, */
  export function InputInt(label: string, value: number, options?: { step?: number; stepFast?: number; flags?: number }): { changed: boolean; value: number };
  /** ImGui::InputInt2(const char* label, int v[2], ImGuiInputTextFlags flags = 0) */
  export function InputInt2(label: string, values: number[], options?: { flags?: number }): { changed: boolean; values: number[] };
  /** ImGui::InputInt3(const char* label, int v[3], ImGuiInputTextFlags flags = 0) */
  export function InputInt3(label: string, values: number[], options?: { flags?: number }): { changed: boolean; values: number[] };
  /** ImGui::InputInt4(const char* label, int v[4], ImGuiInputTextFlags flags = 0) */
  export function InputInt4(label: string, values: number[], options?: { flags?: number }): { changed: boolean; values: number[] };

  // --- Slider Widgets ----------------------------------------------

  /** ImGui::SliderFloat(const char* label, float* v, float v_min, float v_max, */
  export function SliderFloat(label: string, value: number, min: number, max: number, options?: { format?: string; flags?: number }): { changed: boolean; value: number };
  /** ImGui::SliderFloat2(const char* label, float v[2], float v_min, float v_max, */
  export function SliderFloat2(label: string, values: number[], min: number, max: number, options?: { format?: string; flags?: number }): { changed: boolean; values: number[] };
  /** ImGui::SliderFloat3(const char* label, float v[3], float v_min, float v_max, */
  export function SliderFloat3(label: string, values: number[], min: number, max: number, options?: { format?: string; flags?: number }): { changed: boolean; values: number[] };
  /** ImGui::SliderFloat4(const char* label, float v[4], float v_min, float v_max, */
  export function SliderFloat4(label: string, values: number[], min: number, max: number, options?: { format?: string; flags?: number }): { changed: boolean; values: number[] };
  /** ImGui::SliderInt(const char* label, int* v, int v_min, int v_max, const char* */
  export function SliderInt(label: string, value: number, min: number, max: number, options?: { format?: string; flags?: number }): { changed: boolean; value: number };
  /** ImGui::SliderAngle(const char* label, float* v_rad, float v_degrees_min = */
  export function SliderAngle(label: string, v_rad: number, options?: { minDegrees?: number; maxDegrees?: number; format?: string; flags?: number }): { changed: boolean; value: number };

  // --- Drag Widgets ------------------------------------------------

  /** ImGui::DragFloat(const char* label, float* v, float v_speed = 1.0f, float */
  export function DragFloat(label: string, value: number, options?: { speed?: number; min?: number; max?: number; format?: string; flags?: number }): { changed: boolean; value: number };
  /** ImGui::DragFloat2(const char* label, float v[2], float v_speed = 1.0f, float */
  export function DragFloat2(label: string, values: number[], options?: { speed?: number; min?: number; max?: number; format?: string; flags?: number }): { changed: boolean; values: number[] };
  /** ImGui::DragInt(const char* label, int* v, float v_speed = 1.0f, int v_min = */
  export function DragInt(label: string, value: number, options?: { speed?: number; min?: number; max?: number; format?: string; flags?: number }): { changed: boolean; value: number };

  // --- Color Editors and Pickers -----------------------------------

  /** ImGui::ColorEdit3(const char* label, float col[3], ImGuiColorEditFlags flags */
  export function ColorEdit3(label: string, color: number[], flags?: number): { changed: boolean; color: number[] };
  /** ImGui::ColorEdit4(const char* label, float col[4], ImGuiColorEditFlags flags */
  export function ColorEdit4(label: string, color: number[], flags?: number): { changed: boolean; color: number[] };
  /** ImGui::ColorPicker3(const char* label, float col[3], ImGuiColorEditFlags */
  export function ColorPicker3(label: string, color: number[], flags?: number): { changed: boolean; color: number[] };
  /** ImGui::ColorPicker4(const char* label, float col[4], ImGuiColorEditFlags */
  export function ColorPicker4(label: string, col: number[], flags?: number, ref_col?: number[]): { changed: boolean; color: number[] };
  /** ImGui::ColorButton(const char* desc_id, const ImVec4& col, */
  export function ColorButton(desc_id: string, color: number[], options?: { flags?: number; size?: Vec2 }): boolean;
  /** ImGui::SetColorEditOptions(ImGuiColorEditFlags flags) */
  export function SetColorEditOptions(flags: number): void;

  // --- Layout Functions --------------------------------------------

  /** ImGui::Separator() - void */
  export function Separator(): void;
  /** ImGui::SameLine(float offset_from_start_x=0.0f, float spacing=-1.0f) - void */
  export function SameLine(offset_from_start_x?: number, spacing?: number): void;
  /** ImGui::NewLine() - void */
  export function NewLine(): void;
  /** ImGui::Spacing() - void */
  export function Spacing(): void;
  /** ImGui::Indent(float indent_w = 0.0f) - void */
  export function Indent(indent_w?: number): void;
  /** ImGui::Unindent(float indent_w = 0.0f) - void */
  export function Unindent(indent_w?: number): void;

  // --- Cursor Positioning Functions --------------------------------

  /** ImGui::GetCursorScreenPos() - returns ImVec2 */
  export function GetCursorScreenPos(): Vec2;
  /** ImGui::SetCursorScreenPos(const ImVec2& pos) - void */
  export function SetCursorScreenPos(pos: Vec2): void;
  /** ImGui::GetContentRegionAvail() - returns ImVec2 */
  export function GetContentRegionAvail(): Vec2;
  /** ImGui::GetCursorPos() - returns ImVec2 */
  export function GetCursorPos(): Vec2;
  /** ImGui::GetCursorPosX() - returns float */
  export function GetCursorPosX(): number;
  /** ImGui::GetCursorPosY() - returns float */
  export function GetCursorPosY(): number;
  /** ImGui::SetCursorPos(const ImVec2& local_pos) - void */
  export function SetCursorPos(local_pos: Vec2): void;
  /** ImGui::SetCursorPosX(float local_x) - void */
  export function SetCursorPosX(local_x: number): void;
  /** ImGui::SetCursorPosY(float local_y) - void */
  export function SetCursorPosY(local_y: number): void;
  /** ImGui::GetCursorStartPos() - returns ImVec2 */
  export function GetCursorStartPos(): Vec2;

  // --- Scrolling Functions -----------------------------------------

  /** ImGui::GetScrollX() - returns float */
  export function GetScrollX(): number;
  /** ImGui::GetScrollY() - returns float */
  export function GetScrollY(): number;
  /** ImGui::SetScrollX(float scroll_x) - void */
  export function SetScrollX(scroll_x: number): void;
  /** ImGui::SetScrollY(float scroll_y) - void */
  export function SetScrollY(scroll_y: number): void;
  /** ImGui::GetScrollMaxX() - returns float */
  export function GetScrollMaxX(): number;
  /** ImGui::GetScrollMaxY() - returns float */
  export function GetScrollMaxY(): number;
  /** ImGui::SetScrollHereX(float center_x_ratio = 0.5f) - void */
  export function SetScrollHereX(center_x_ratio?: number): void;
  /** ImGui::SetScrollHereY(float center_y_ratio = 0.5f) - void */
  export function SetScrollHereY(center_y_ratio?: number): void;

  // --- Menu Functions ----------------------------------------------

  /** ImGui::BeginMenuBar() - returns bool */
  export function BeginMenuBar(): boolean;
  /** ImGui::EndMenuBar() - void */
  export function EndMenuBar(): void;
  /** ImGui::BeginMainMenuBar() - returns bool */
  export function BeginMainMenuBar(): boolean;
  /** ImGui::EndMainMenuBar() - void */
  export function EndMainMenuBar(): void;
  /** ImGui::BeginMenu(const char* label, bool enabled = true) - returns bool */
  export function BeginMenu(label: string, enabled?: boolean): boolean;
  /** ImGui::EndMenu() - void */
  export function EndMenu(): void;
  /** ImGui::MenuItem(const char* label, const char* shortcut = NULL, bool selected */
  export function MenuItem(label: string, options?: { shortcut?: string; selected?: boolean; enabled?: boolean }): { clicked: boolean; selected: boolean } | boolean;

  // --- Popup and Modal Functions -----------------------------------

  /** ImGui::BeginPopup(const char* str_id, ImGuiWindowFlags flags = 0) - returns */
  export function BeginPopup(str_id: string, flags?: number): boolean;
  /** ImGui::BeginPopupModal(const char* name, bool* p_open = NULL, */
  export function BeginPopupModal(name: string, options?: { open?: boolean; flags?: number }): { result: boolean; open: boolean } | boolean;
  /** ImGui::EndPopup() - void */
  export function EndPopup(): void;
  /** ImGui::OpenPopup(const char* str_id, ImGuiPopupFlags popup_flags = 0) - void */
  export function OpenPopup(str_id: string, popup_flags?: number): void;
  /** ImGui::OpenPopupOnItemClick(const char* str_id = NULL, ImGuiPopupFlags */
  export function OpenPopupOnItemClick(str_id?: string, popup_flags?: number): void;
  /** ImGui::CloseCurrentPopup() - void */
  export function CloseCurrentPopup(): void;
  /** ImGui::BeginPopupContextItem(const char* str_id = NULL, ImGuiPopupFlags */
  export function BeginPopupContextItem(str_id?: string, popup_flags?: number): boolean;
  /** ImGui::BeginPopupContextVoid(const char* str_id = NULL, ImGuiPopupFlags */
  export function BeginPopupContextVoid(str_id?: string, popup_flags?: number): boolean;
  /** ImGui::IsPopupOpen(const char* str_id, ImGuiPopupFlags flags = 0) - returns */
  export function IsPopupOpen(str_id: string, flags?: number): boolean;

  // --- Tooltip Functions -------------------------------------------

  /** ImGui::BeginTooltip() - returns bool */
  export function BeginTooltip(): boolean;
  /** ImGui::EndTooltip() - void */
  export function EndTooltip(): void;
  /** ImGui::SetTooltip(const char* fmt, ...) - void */
  export function SetTooltip(text: string): void;
  /** ImGui::BeginItemTooltip() - returns bool */
  export function BeginItemTooltip(): boolean;
  /** ImGui::SetItemTooltip(const char* fmt, ...) - void */
  export function SetItemTooltip(text: string): void;

  // --- Window Functions --------------------------------------------

  /** ImGui::Begin(const char* name, bool* p_open = NULL, ImGuiWindowFlags flags = */
  export function Begin(name: string, options?: { open?: boolean; flags?: number }): { result: boolean; open: boolean } | boolean;
  /** ImGui::End() - void */
  export function End(): void;
  /** ImGui::BeginChild - two overloads merged */
  export function BeginChild(id: string | number, options?: { size?: Vec2; childFlags?: number; windowFlags?: number }): boolean;
  /** ImGui::EndChild() - void */
  export function EndChild(): void;

  // --- Window Utilities --------------------------------------------

  /** ImGui::IsWindowAppearing() - returns bool */
  export function IsWindowAppearing(): boolean;
  /** ImGui::IsWindowCollapsed() - returns bool */
  export function IsWindowCollapsed(): boolean;
  /** ImGui::IsWindowFocused(ImGuiFocusedFlags flags=0) - returns bool */
  export function IsWindowFocused(flags?: number): boolean;
  /** ImGui::IsWindowHovered(ImGuiHoveredFlags flags=0) - returns bool */
  export function IsWindowHovered(flags?: number): boolean;
  /** ImGui::GetWindowPos() - returns ImVec2 */
  export function GetWindowPos(): Vec2;
  /** ImGui::GetWindowSize() - returns ImVec2 */
  export function GetWindowSize(): Vec2;
  /** ImGui::GetWindowWidth() - returns float */
  export function GetWindowWidth(): number;
  /** ImGui::GetWindowHeight() - returns float */
  export function GetWindowHeight(): number;

  // --- Window Manipulation -----------------------------------------

  /** ImGui::SetNextWindowPos(const ImVec2& pos, ImGuiCond cond = 0, const ImVec2& */
  export function SetNextWindowPos(pos: Vec2, options?: { cond?: number; pivot?: Vec2 }): void;
  /** ImGui::SetNextWindowSize(const ImVec2& size, ImGuiCond cond = 0) */
  export function SetNextWindowSize(size: Vec2, options?: { cond?: number }): void;
  /** ImGui::SetNextWindowCollapsed(bool collapsed, ImGuiCond cond = 0) */
  export function SetNextWindowCollapsed(collapsed: boolean, options?: { cond?: number }): void;
  /** ImGui::SetNextWindowFocus() - void */
  export function SetNextWindowFocus(): void;
  /** ImGui::SetNextWindowBgAlpha(float alpha) - void */
  export function SetNextWindowBgAlpha(alpha: number): void;

  // --- Style Functions ---------------------------------------------

  /** ImGui::PushStyleColor(ImGuiCol idx, ImU32 col) */
  export function PushStyleColor(idx: number, col: number | Vec4): void;
  /** ImGui::PopStyleColor(int count = 1) */
  export function PopStyleColor(count?: number): void;
  /** ImGui::PushStyleVar(ImGuiStyleVar idx, float val) */
  export function PushStyleVar(idx: number, val: number | Vec2): void;
  /** ImGui::PushStyleVarX(ImGuiStyleVar idx, float val_x) */
  export function PushStyleVarX(idx: number, val_x: number): void;
  /** ImGui::PushStyleVarY(ImGuiStyleVar idx, float val_y) */
  export function PushStyleVarY(idx: number, val_y: number): void;
  /** ImGui::PopStyleVar(int count = 1) */
  export function PopStyleVar(count?: number): void;

  // --- Item Functions ----------------------------------------------

  /** ImGui::PushItemFlag(ImGuiItemFlags option, bool enabled) */
  export function PushItemFlag(option: number, enabled: boolean): void;
  /** ImGui::PopItemFlag() */
  export function PopItemFlag(): void;
  /** ImGui::PushItemWidth(float item_width) */
  export function PushItemWidth(item_width: number): void;
  /** ImGui::PopItemWidth() */
  export function PopItemWidth(): void;
  /** ImGui::SetNextItemWidth(float item_width) */
  export function SetNextItemWidth(item_width: number): void;
  /** ImGui::CalcItemWidth() */
  export function CalcItemWidth(): number;
  /** ImGui::PushTextWrapPos(float wrap_local_pos_x = 0.0f) */
  export function PushTextWrapPos(wrap_local_pos_x?: number): void;
  /** ImGui::PopTextWrapPos() */
  export function PopTextWrapPos(): void;

  // --- Font Functions ----------------------------------------------

  /** ImGui::PushFont(ImFont* font) */
  export function PushFont(): void;
  /** ImGui::PopFont() */
  export function PopFont(): void;
  /** ImGui::GetFont() */
  export function GetFont(): null;
  /** ImGui::GetFontSize() */
  export function GetFontSize(): number;
  /** ImGui::GetFontTexUvWhitePixel() */
  export function GetFontTexUvWhitePixel(): Vec2;

  // --- Color Functions ---------------------------------------------

  /** ImGui::GetColorU32(ImGuiCol idx, float alpha_mul = 1.0f) */
  export function GetColorU32(col_or_idx: number | Vec4, alpha_mul?: number): number;
  /** ImGui::GetStyleColorVec4(ImGuiCol idx) */
  export function GetStyleColorVec4(idx: number): Vec4;

  // --- Table Creation ----------------------------------------------

  /** ImGui::BeginTable(const char* str_id, int column, ImGuiTableFlags flags = 0, */
  export function BeginTable(str_id: string, column: number, options?: { flags?: number; outerSize?: Vec2; innerWidth?: number }): boolean;
  /** ImGui::EndTable() - void */
  export function EndTable(): void;
  /** ImGui::TableNextRow(ImGuiTableRowFlags row_flags = 0, float min_row_height = */
  export function TableNextRow(options?: { rowFlags?: number; minRowHeight?: number }): void;
  /** ImGui::TableNextColumn() - returns bool */
  export function TableNextColumn(): boolean;
  /** ImGui::TableSetColumnIndex(int column_n) - returns bool */
  export function TableSetColumnIndex(column_n: number): boolean;

  // --- Table Setup -------------------------------------------------

  /** ImGui::TableSetupColumn(const char* label, ImGuiTableColumnFlags flags = 0, */
  export function TableSetupColumn(label: string, options?: { flags?: number; initWidthOrWeight?: number; userId?: number }): void;
  /** ImGui::TableSetupScrollFreeze(int cols, int rows) - void */
  export function TableSetupScrollFreeze(cols: number, rows: number): void;
  /** ImGui::TableHeader(const char* label) - void */
  export function TableHeader(label: string): void;
  /** ImGui::TableHeadersRow() - void */
  export function TableHeadersRow(): void;
  /** ImGui::TableAngledHeadersRow() - void */
  export function TableAngledHeadersRow(): void;

  // --- Table Query -------------------------------------------------

  /** ImGui::TableGetColumnCount() - returns int */
  export function TableGetColumnCount(): number;
  /** ImGui::TableGetColumnIndex() - returns int */
  export function TableGetColumnIndex(): number;
  /** ImGui::TableGetRowIndex() - returns int */
  export function TableGetRowIndex(): number;
  /** ImGui::TableGetColumnName(int column_n = -1) - returns const char* */
  export function TableGetColumnName(column_n?: number): string | null;
  /** ImGui::TableGetColumnFlags(int column_n = -1) - returns ImGuiTableColumnFlags */
  export function TableGetColumnFlags(column_n?: number): number;
  /** ImGui::TableSetBgColor(ImGuiTableBgTarget target, ImU32 color, int column_n = */
  export function TableSetBgColor(target: number, color: number, options?: { columnN?: number }): void;

  // --- Table Sorting -----------------------------------------------

  /** ImGui::TableGetSortSpecs() - returns ImGuiTableSortSpecs* */
  export function TableGetSortSpecs(): null | any | { specsCount: number; specsDirty: boolean };

  // --- Item/Widget Queries -----------------------------------------

  /** ImGui::IsItemHovered(ImGuiHoveredFlags flags = 0) */
  export function IsItemHovered(flags?: number): boolean;
  /** ImGui::IsItemActive() */
  export function IsItemActive(): boolean;
  /** ImGui::IsItemFocused() */
  export function IsItemFocused(): boolean;
  /** ImGui::IsItemClicked(ImGuiMouseButton mouse_button = 0) */
  export function IsItemClicked(mouse_button?: number): boolean;
  /** ImGui::IsItemVisible() */
  export function IsItemVisible(): boolean;
  /** ImGui::IsItemEdited() */
  export function IsItemEdited(): boolean;
  /** ImGui::IsItemActivated() */
  export function IsItemActivated(): boolean;
  /** ImGui::IsItemDeactivated() */
  export function IsItemDeactivated(): boolean;
  /** ImGui::IsItemToggledOpen() */
  export function IsItemToggledOpen(): boolean;
  /** ImGui::IsAnyItemHovered() */
  export function IsAnyItemHovered(): boolean;
  /** ImGui::IsAnyItemActive() */
  export function IsAnyItemActive(): boolean;
  /** ImGui::IsAnyItemFocused() */
  export function IsAnyItemFocused(): boolean;
  /** ImGui::GetItemRectMin() */
  export function GetItemRectMin(): Vec2;
  /** ImGui::GetItemRectMax() */
  export function GetItemRectMax(): Vec2;
  /** ImGui::GetItemRectSize() */
  export function GetItemRectSize(): Vec2;

  // --- Keyboard/Mouse/Gamepad Queries ------------------------------

  /** ImGui::IsKeyDown(ImGuiKey key) */
  export function IsKeyDown(key: number): boolean;
  /** ImGui::IsKeyPressed(ImGuiKey key, bool repeat = true) */
  export function IsKeyPressed(key: number, repeat?: boolean): boolean;
  /** ImGui::IsKeyReleased(ImGuiKey key) */
  export function IsKeyReleased(key: number): boolean;
  /** ImGui::IsMouseDown(ImGuiMouseButton button) */
  export function IsMouseDown(button: number): boolean;
  /** ImGui::IsMouseClicked(ImGuiMouseButton button, bool repeat = false) */
  export function IsMouseClicked(button: number, repeat?: boolean): boolean;
  /** ImGui::IsMouseReleased(ImGuiMouseButton button) */
  export function IsMouseReleased(button: number): boolean;
  /** ImGui::IsMouseDoubleClicked(ImGuiMouseButton button) */
  export function IsMouseDoubleClicked(button: number): boolean;
  /** ImGui::IsMouseDragging(ImGuiMouseButton button, float lock_threshold = -1.0f) */
  export function IsMouseDragging(button: number, lock_threshold?: number): boolean;
  /** ImGui::GetMousePos() */
  export function GetMousePos(): Vec2;
  /** ImGui::GetMouseDragDelta(ImGuiMouseButton button = 0, float lock_threshold = */
  export function GetMouseDragDelta(button?: number, lock_threshold?: number): Vec2;
  /** ImGui::ResetMouseDragDelta(ImGuiMouseButton button = 0) */
  export function ResetMouseDragDelta(button?: number): void;

  // --- Clipboard ---------------------------------------------------

  /** ImGui::GetClipboardText() */
  export function GetClipboardText(): string;
  /** ImGui::SetClipboardText(const char* text) */
  export function SetClipboardText(text: string): void;

  // --- Miscellaneous Utilities -------------------------------------

  /** ImGui::SetItemDefaultFocus() */
  export function SetItemDefaultFocus(): void;
  /** ImGui::SetKeyboardFocusHere(int offset = 0) */
  export function SetKeyboardFocusHere(offset?: number): void;
  /** ImGui::Shortcut(ImGuiKeyChord key_chord, ImGuiInputFlags flags = 0) */
  export function Shortcut(key_chord: number, flags?: number): boolean;
  /** ImGui::SetNextItemShortcut(ImGuiKeyChord key_chord, ImGuiInputFlags flags = */
  export function SetNextItemShortcut(key_chord: number, flags?: number): void;
  /** ImGui::BeginDisabled(bool disabled = true) */
  export function BeginDisabled(disabled?: boolean): void;
  /** ImGui::EndDisabled() */
  export function EndDisabled(): void;

  // --- Tree Nodes --------------------------------------------------

  /** ImGui::TreeNode(const char* label) */
  export function TreeNode(label: string): boolean;
  /** ImGui::TreeNode(const char* str_id, const char* fmt, ...) */
  export function TreeNodeV(str_id: string, label: string): boolean;
  /** ImGui::TreeNodeEx(const char* label, ImGuiTreeNodeFlags flags = 0) */
  export function TreeNodeEx(label: string, flags?: number): boolean;
  /** ImGui::TreeNodeEx(const char* str_id, ImGuiTreeNodeFlags flags, const char* */
  export function TreeNodeEx2(str_id: string, flags: number, label: string): boolean;
  /** ImGui::TreePush(const char* str_id) */
  export function TreePush(str_id: string): void;
  /** ImGui::TreePush(const void* ptr_id) */
  export function TreePushPtr(id_num: number): void;
  /** ImGui::TreePop() */
  export function TreePop(): void;
  /** ImGui::CollapsingHeader(const char* label, ImGuiTreeNodeFlags flags = 0) */
  export function CollapsingHeader(label: string, flags?: number): boolean;
  /** ImGui::CollapsingHeader(const char* label, bool* p_visible, */
  export function CollapsingHeaderEx(label: string, visible: boolean, flags?: number): { opened: boolean; visible: boolean };
  /** ImGui::SetNextItemOpen(bool is_open, ImGuiCond cond = 0) */
  export function SetNextItemOpen(is_open: boolean, cond?: number): void;

  // --- Selectables -------------------------------------------------

  /** ImGui::Selectable(const char* label, bool selected = false, */
  export function Selectable(label: string, options?: { selected?: boolean; flags?: number; size?: Vec2 }): boolean;
  /** ImGui::Selectable(const char* label, bool* p_selected, ImGuiSelectableFlags */
  export function SelectableEx(label: string, selected: boolean, options?: { flags?: number; size?: Vec2 }): { clicked: boolean; selected: boolean };

  // --- List Boxes --------------------------------------------------

  /** ImGui::BeginListBox(const char* label, const ImVec2& size = ImVec2(0,0)) */
  export function BeginListBox(label: string, options?: { size?: Vec2 }): boolean;
  /** ImGui::EndListBox() */
  export function EndListBox(): void;
  /** ImGui::ListBox(const char* label, int* current_item, const char* const */
  export function ListBox(label: string, current_item: number, items: string[], height_in_items?: number): { changed: boolean; current_item: number };

  // --- Combos ------------------------------------------------------

  /** ImGui::BeginCombo(const char* label, const char* preview_value, */
  export function BeginCombo(label: string, preview_value: string, flags?: number): boolean;
  /** ImGui::EndCombo() */
  export function EndCombo(): void;
  /** ImGui::Combo(const char* label, int* current_item, const char* const items[], */
  export function Combo(label: string, current_item: number, items: string[], popup_max_height_in_items?: number): { changed: boolean; current_item: number };
  /** ImGui::Combo(const char* label, int* current_item, const char* */
  export function ComboSimple(label: string, current_item: number, items_separated_by_zeros: string, popup_max_height_in_items?: number): { changed: boolean; current_item: number };
}
