schema_version = "1.0.0"

id = "io_scene_rif"
version = "0.1.0"
name = "Gunlok RIF"
tagline = "Import and export Rebellion RIF assets used by Gunlok (2000)"
maintainer = "GkPlus"
type = "add-on"

blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]

tags = ["Import-Export"]
