#!/usr/bin/env python3
"""Stand in for a generated API tree that this build could not produce.

    python3 docs/tools/api-placeholder.py cpp

Writes `docs/static/api/<name>/index.html` if, and only if, that tree has no
`index.html` of its own. An existing generated tree is never touched.

This exists for one case. The C++ reference is produced by clang-doc from
`build/compile_commands.json`, and `CMakeLists.txt` refuses to configure
anywhere but 32-bit Windows, so a Linux CI runner cannot produce it. Without
this, every `/api/cpp/...` link on the site (the header, the footer, and the
prose on the C++ reference pages) would 404 in the published build.

A placeholder is the honest answer: the links stay valid, and a reader who
follows one is told what is missing and how to generate it, rather than meeting
a 404 and concluding the documentation is broken.

Run it before `unify-api.py`, which then gives the page the site's own header
bar and stylesheets like any other generated page.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

API = Path(__file__).resolve().parent.parent / "static" / "api"

TREES = {
    "cpp": {
        "title": "C++ API reference",
        "generator": "clang-doc",
        "why": (
            "This build could not generate it. clang-doc reads "
            "<code>build/compile_commands.json</code>, and GkPlus configures only as a "
            "32-bit Windows target &mdash; <code>CMakeLists.txt</code> stops with "
            "<code>FATAL_ERROR</code> anywhere else &mdash; so a Linux runner has no "
            "compilation database to read."
        ),
        "how": [
            "cmake --preset builtin-vcpkg",
            "clang-doc --executor=all-TUs build/compile_commands.json --format=html \\",
            "  --output=docs/static/api/cpp --project-name=GkPlus --public \\",
            "  --ignore-map-errors --extra-arg=-Xclang \\",
            "  --extra-arg=-fparse-all-comments --extra-arg=-ferror-limit=0",
            "python3 docs/tools/unify-api.py",
        ],
        "instead": [
            ("/reference/cpp/", "The C++ reference section"),
            ("/reference/cpp/namespaces/", "The namespace map"),
        ],
    },
    "js": {
        "title": "JavaScript API reference",
        "generator": "TypeDoc",
        "why": "This build could not generate it.",
        "how": [
            "npx -y -p typedoc@0.28 -p typescript@5.9 typedoc --options types/typedoc.json",
            "python3 docs/tools/unify-api.py",
        ],
        "instead": [("/reference/javascript/", "The JavaScript reference section")],
    },
}

PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} &middot; not in this build</title>
<meta name="robots" content="noindex">
<!-- This is a hand-written page using the site's own classes, so it links the
     site stylesheet. unify-api.py adds the tokens and the API skin after these,
     which is the order that makes the header bar match too. -->
<link rel="stylesheet" href="/css/gkplus-tokens.css">
<link rel="stylesheet" href="/css/gkplus.css">
</head>
<body>
<main class="gk-wrap" style="display:block;max-width:52rem">
  <span class="gk-eyebrow">Reference</span>
  <h1>{title}</h1>
  <p class="gk-lede">Generated by {generator}, and not present in this build of the site.</p>
  <p>{why}</p>
  <h2>Generating it</h2>
  <p>From a configured checkout on Windows:</p>
  <pre><code>{how}</code></pre>
  <h2>In the meantime</h2>
  <ul>
{instead}
  </ul>
</main>
</body>
</html>
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("name", choices=sorted(TREES), help="which tree to stand in for")
    args = ap.parse_args()

    spec = TREES[args.name]
    out = API / args.name / "index.html"
    if out.exists():
        print(f"api-placeholder: {out.parent.name}/ was generated - leaving it alone")
        return 0

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(PAGE.format(
        title=spec["title"],
        generator=spec["generator"],
        why=spec["why"],
        how="\n".join(spec["how"]),
        instead="\n".join(f'    <li><a href="{u}">{t}</a></li>' for u, t in spec["instead"]),
    ), encoding="utf-8")
    print(f"api-placeholder: wrote {out.relative_to(API.parent.parent)} "
          f"({spec['generator']} output is absent)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
