// Generated by src/gen-d3d8-forwarders.py from d3d8to9's d3d8.hpp. Do not edit.
//
// X is invoked as X(ret, Name, (params), (args)). See the generator's docstring.
#pragma once

// IDirect3D8: all methods
#define GK_IDIRECT3D8_METHODS(X) \
  X(HRESULT, RegisterSoftwareDevice, (void *pInitializeFunction), (pInitializeFunction)) \
  X(UINT, GetAdapterCount, (), ()) \
  X(HRESULT, GetAdapterIdentifier, (UINT Adapter, DWORD Flags, D3DADAPTER_IDENTIFIER8 *pIdentifier), (Adapter, Flags, pIdentifier)) \
  X(UINT, GetAdapterModeCount, (UINT Adapter), (Adapter)) \
  X(HRESULT, EnumAdapterModes, (UINT Adapter, UINT Mode, D3DDISPLAYMODE *pMode), (Adapter, Mode, pMode)) \
  X(HRESULT, GetAdapterDisplayMode, (UINT Adapter, D3DDISPLAYMODE *pMode), (Adapter, pMode)) \
  X(HRESULT, CheckDeviceType, (UINT Adapter, D3DDEVTYPE CheckType, D3DFORMAT DisplayFormat, D3DFORMAT BackBufferFormat, BOOL bWindowed), (Adapter, CheckType, DisplayFormat, BackBufferFormat, bWindowed)) \
  X(HRESULT, CheckDeviceFormat, (UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, DWORD Usage, D3DRESOURCETYPE RType, D3DFORMAT CheckFormat), (Adapter, DeviceType, AdapterFormat, Usage, RType, CheckFormat)) \
  X(HRESULT, CheckDeviceMultiSampleType, (UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT SurfaceFormat, BOOL Windowed, D3DMULTISAMPLE_TYPE MultiSampleType), (Adapter, DeviceType, SurfaceFormat, Windowed, MultiSampleType)) \
  X(HRESULT, CheckDepthStencilMatch, (UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, D3DFORMAT RenderTargetFormat, D3DFORMAT DepthStencilFormat), (Adapter, DeviceType, AdapterFormat, RenderTargetFormat, DepthStencilFormat)) \
  X(HRESULT, GetDeviceCaps, (UINT Adapter, D3DDEVTYPE DeviceType, D3DCAPS8 *pCaps), (Adapter, DeviceType, pCaps)) \
  X(HMONITOR, GetAdapterMonitor, (UINT Adapter), (Adapter)) \
  X(HRESULT, CreateDevice, (UINT Adapter, D3DDEVTYPE DeviceType, HWND hFocusWindow, DWORD BehaviorFlags, D3DPRESENT_PARAMETERS8 *pPresentationParameters, IDirect3DDevice8 **ppReturnedDeviceInterface), (Adapter, DeviceType, hFocusWindow, BehaviorFlags, pPresentationParameters, ppReturnedDeviceInterface))

// IDirect3D8: pass-through only
#define GK_IDIRECT3D8_FORWARDED(X) \
  X(HRESULT, RegisterSoftwareDevice, (void *pInitializeFunction), (pInitializeFunction)) \
  X(UINT, GetAdapterCount, (), ()) \
  X(HRESULT, GetAdapterIdentifier, (UINT Adapter, DWORD Flags, D3DADAPTER_IDENTIFIER8 *pIdentifier), (Adapter, Flags, pIdentifier)) \
  X(UINT, GetAdapterModeCount, (UINT Adapter), (Adapter)) \
  X(HRESULT, EnumAdapterModes, (UINT Adapter, UINT Mode, D3DDISPLAYMODE *pMode), (Adapter, Mode, pMode)) \
  X(HRESULT, GetAdapterDisplayMode, (UINT Adapter, D3DDISPLAYMODE *pMode), (Adapter, pMode)) \
  X(HRESULT, CheckDeviceType, (UINT Adapter, D3DDEVTYPE CheckType, D3DFORMAT DisplayFormat, D3DFORMAT BackBufferFormat, BOOL bWindowed), (Adapter, CheckType, DisplayFormat, BackBufferFormat, bWindowed)) \
  X(HRESULT, CheckDeviceFormat, (UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, DWORD Usage, D3DRESOURCETYPE RType, D3DFORMAT CheckFormat), (Adapter, DeviceType, AdapterFormat, Usage, RType, CheckFormat)) \
  X(HRESULT, CheckDeviceMultiSampleType, (UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT SurfaceFormat, BOOL Windowed, D3DMULTISAMPLE_TYPE MultiSampleType), (Adapter, DeviceType, SurfaceFormat, Windowed, MultiSampleType)) \
  X(HRESULT, CheckDepthStencilMatch, (UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, D3DFORMAT RenderTargetFormat, D3DFORMAT DepthStencilFormat), (Adapter, DeviceType, AdapterFormat, RenderTargetFormat, DepthStencilFormat)) \
  X(HRESULT, GetDeviceCaps, (UINT Adapter, D3DDEVTYPE DeviceType, D3DCAPS8 *pCaps), (Adapter, DeviceType, pCaps)) \
  X(HMONITOR, GetAdapterMonitor, (UINT Adapter), (Adapter))

// IDirect3DDevice8: all methods
#define GK_IDIRECT3DDEVICE8_METHODS(X) \
  X(HRESULT, TestCooperativeLevel, (), ()) \
  X(UINT, GetAvailableTextureMem, (), ()) \
  X(HRESULT, ResourceManagerDiscardBytes, (DWORD Bytes), (Bytes)) \
  X(HRESULT, GetDirect3D, (IDirect3D8 **ppD3D8), (ppD3D8)) \
  X(HRESULT, GetDeviceCaps, (D3DCAPS8 *pCaps), (pCaps)) \
  X(HRESULT, GetDisplayMode, (D3DDISPLAYMODE *pMode), (pMode)) \
  X(HRESULT, GetCreationParameters, (D3DDEVICE_CREATION_PARAMETERS *pParameters), (pParameters)) \
  X(HRESULT, SetCursorProperties, (UINT XHotSpot, UINT YHotSpot, IDirect3DSurface8 *pCursorBitmap), (XHotSpot, YHotSpot, pCursorBitmap)) \
  X(void, SetCursorPosition, (UINT XScreenSpace, UINT YScreenSpace, DWORD Flags), (XScreenSpace, YScreenSpace, Flags)) \
  X(BOOL, ShowCursor, (BOOL bShow), (bShow)) \
  X(HRESULT, CreateAdditionalSwapChain, (D3DPRESENT_PARAMETERS8 *pPresentationParameters, IDirect3DSwapChain8 **ppSwapChain), (pPresentationParameters, ppSwapChain)) \
  X(HRESULT, Reset, (D3DPRESENT_PARAMETERS8 *pPresentationParameters), (pPresentationParameters)) \
  X(HRESULT, Present, (const RECT *pSourceRect, const RECT *pDestRect, HWND hDestWindowOverride, const RGNDATA *pDirtyRegion), (pSourceRect, pDestRect, hDestWindowOverride, pDirtyRegion)) \
  X(HRESULT, GetBackBuffer, (UINT iBackBuffer, D3DBACKBUFFER_TYPE Type, IDirect3DSurface8 **ppBackBuffer), (iBackBuffer, Type, ppBackBuffer)) \
  X(HRESULT, GetRasterStatus, (D3DRASTER_STATUS *pRasterStatus), (pRasterStatus)) \
  X(void, SetGammaRamp, (DWORD Flags, const D3DGAMMARAMP *pRamp), (Flags, pRamp)) \
  X(void, GetGammaRamp, (D3DGAMMARAMP *pRamp), (pRamp)) \
  X(HRESULT, CreateTexture, (UINT Width, UINT Height, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DTexture8 **ppTexture), (Width, Height, Levels, Usage, Format, Pool, ppTexture)) \
  X(HRESULT, CreateVolumeTexture, (UINT Width, UINT Height, UINT Depth, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DVolumeTexture8 **ppVolumeTexture), (Width, Height, Depth, Levels, Usage, Format, Pool, ppVolumeTexture)) \
  X(HRESULT, CreateCubeTexture, (UINT EdgeLength, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DCubeTexture8 **ppCubeTexture), (EdgeLength, Levels, Usage, Format, Pool, ppCubeTexture)) \
  X(HRESULT, CreateVertexBuffer, (UINT Length, DWORD Usage, DWORD FVF, D3DPOOL Pool, IDirect3DVertexBuffer8 **ppVertexBuffer), (Length, Usage, FVF, Pool, ppVertexBuffer)) \
  X(HRESULT, CreateIndexBuffer, (UINT Length, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DIndexBuffer8 **ppIndexBuffer), (Length, Usage, Format, Pool, ppIndexBuffer)) \
  X(HRESULT, CreateRenderTarget, (UINT Width, UINT Height, D3DFORMAT Format, D3DMULTISAMPLE_TYPE MultiSample, BOOL Lockable, IDirect3DSurface8 **ppSurface), (Width, Height, Format, MultiSample, Lockable, ppSurface)) \
  X(HRESULT, CreateDepthStencilSurface, (UINT Width, UINT Height, D3DFORMAT Format, D3DMULTISAMPLE_TYPE MultiSample, IDirect3DSurface8 **ppSurface), (Width, Height, Format, MultiSample, ppSurface)) \
  X(HRESULT, CreateImageSurface, (UINT Width, UINT Height, D3DFORMAT Format, IDirect3DSurface8 **ppSurface), (Width, Height, Format, ppSurface)) \
  X(HRESULT, CopyRects, (IDirect3DSurface8 *pSourceSurface, const RECT *pSourceRectsArray, UINT cRects, IDirect3DSurface8 *pDestinationSurface, const POINT *pDestPointsArray), (pSourceSurface, pSourceRectsArray, cRects, pDestinationSurface, pDestPointsArray)) \
  X(HRESULT, UpdateTexture, (IDirect3DBaseTexture8 *pSourceTexture, IDirect3DBaseTexture8 *pDestinationTexture), (pSourceTexture, pDestinationTexture)) \
  X(HRESULT, GetFrontBuffer, (IDirect3DSurface8 *pDestSurface), (pDestSurface)) \
  X(HRESULT, SetRenderTarget, (IDirect3DSurface8 *pRenderTarget, IDirect3DSurface8 *pNewZStencil), (pRenderTarget, pNewZStencil)) \
  X(HRESULT, GetRenderTarget, (IDirect3DSurface8 **ppRenderTarget), (ppRenderTarget)) \
  X(HRESULT, GetDepthStencilSurface, (IDirect3DSurface8 **ppZStencilSurface), (ppZStencilSurface)) \
  X(HRESULT, BeginScene, (), ()) \
  X(HRESULT, EndScene, (), ()) \
  X(HRESULT, Clear, (DWORD Count, const D3DRECT *pRects, DWORD Flags, D3DCOLOR Color, float Z, DWORD Stencil), (Count, pRects, Flags, Color, Z, Stencil)) \
  X(HRESULT, SetTransform, (D3DTRANSFORMSTATETYPE State, const D3DMATRIX *pMatrix), (State, pMatrix)) \
  X(HRESULT, GetTransform, (D3DTRANSFORMSTATETYPE State, D3DMATRIX *pMatrix), (State, pMatrix)) \
  X(HRESULT, MultiplyTransform, (D3DTRANSFORMSTATETYPE State, const D3DMATRIX *pMatrix), (State, pMatrix)) \
  X(HRESULT, SetViewport, (const D3DVIEWPORT8 *pViewport), (pViewport)) \
  X(HRESULT, GetViewport, (D3DVIEWPORT8 *pViewport), (pViewport)) \
  X(HRESULT, SetMaterial, (const D3DMATERIAL8 *pMaterial), (pMaterial)) \
  X(HRESULT, GetMaterial, (D3DMATERIAL8 *pMaterial), (pMaterial)) \
  X(HRESULT, SetLight, (DWORD Index, const D3DLIGHT8 *pLight), (Index, pLight)) \
  X(HRESULT, GetLight, (DWORD Index, D3DLIGHT8 *pLight), (Index, pLight)) \
  X(HRESULT, LightEnable, (DWORD Index, BOOL Enable), (Index, Enable)) \
  X(HRESULT, GetLightEnable, (DWORD Index, BOOL *pEnable), (Index, pEnable)) \
  X(HRESULT, SetClipPlane, (DWORD Index, const float *pPlane), (Index, pPlane)) \
  X(HRESULT, GetClipPlane, (DWORD Index, float *pPlane), (Index, pPlane)) \
  X(HRESULT, SetRenderState, (D3DRENDERSTATETYPE State, DWORD Value), (State, Value)) \
  X(HRESULT, GetRenderState, (D3DRENDERSTATETYPE State, DWORD *pValue), (State, pValue)) \
  X(HRESULT, BeginStateBlock, (), ()) \
  X(HRESULT, EndStateBlock, (DWORD *pToken), (pToken)) \
  X(HRESULT, ApplyStateBlock, (DWORD Token), (Token)) \
  X(HRESULT, CaptureStateBlock, (DWORD Token), (Token)) \
  X(HRESULT, DeleteStateBlock, (DWORD Token), (Token)) \
  X(HRESULT, CreateStateBlock, (D3DSTATEBLOCKTYPE Type, DWORD *pToken), (Type, pToken)) \
  X(HRESULT, SetClipStatus, (const D3DCLIPSTATUS8 *pClipStatus), (pClipStatus)) \
  X(HRESULT, GetClipStatus, (D3DCLIPSTATUS8 *pClipStatus), (pClipStatus)) \
  X(HRESULT, GetTexture, (DWORD Stage, IDirect3DBaseTexture8 **ppTexture), (Stage, ppTexture)) \
  X(HRESULT, SetTexture, (DWORD Stage, IDirect3DBaseTexture8 *pTexture), (Stage, pTexture)) \
  X(HRESULT, GetTextureStageState, (DWORD Stage, D3DTEXTURESTAGESTATETYPE Type, DWORD *pValue), (Stage, Type, pValue)) \
  X(HRESULT, SetTextureStageState, (DWORD Stage, D3DTEXTURESTAGESTATETYPE Type, DWORD Value), (Stage, Type, Value)) \
  X(HRESULT, ValidateDevice, (DWORD *pNumPasses), (pNumPasses)) \
  X(HRESULT, GetInfo, (DWORD DevInfoID, void *pDevInfoStruct, DWORD DevInfoStructSize), (DevInfoID, pDevInfoStruct, DevInfoStructSize)) \
  X(HRESULT, SetPaletteEntries, (UINT PaletteNumber, const PALETTEENTRY *pEntries), (PaletteNumber, pEntries)) \
  X(HRESULT, GetPaletteEntries, (UINT PaletteNumber, PALETTEENTRY *pEntries), (PaletteNumber, pEntries)) \
  X(HRESULT, SetCurrentTexturePalette, (UINT PaletteNumber), (PaletteNumber)) \
  X(HRESULT, GetCurrentTexturePalette, (UINT *PaletteNumber), (PaletteNumber)) \
  X(HRESULT, DrawPrimitive, (D3DPRIMITIVETYPE PrimitiveType, UINT StartVertex, UINT PrimitiveCount), (PrimitiveType, StartVertex, PrimitiveCount)) \
  X(HRESULT, DrawIndexedPrimitive, (D3DPRIMITIVETYPE PrimitiveType, UINT MinIndex, UINT NumVertices, UINT StartIndex, UINT PrimitiveCount), (PrimitiveType, MinIndex, NumVertices, StartIndex, PrimitiveCount)) \
  X(HRESULT, DrawPrimitiveUP, (D3DPRIMITIVETYPE PrimitiveType, UINT PrimitiveCount, const void *pVertexStreamZeroData, UINT VertexStreamZeroStride), (PrimitiveType, PrimitiveCount, pVertexStreamZeroData, VertexStreamZeroStride)) \
  X(HRESULT, DrawIndexedPrimitiveUP, (D3DPRIMITIVETYPE PrimitiveType, UINT MinVertexIndex, UINT NumVertexIndices, UINT PrimitiveCount, const void *pIndexData, D3DFORMAT IndexDataFormat, const void *pVertexStreamZeroData, UINT VertexStreamZeroStride), (PrimitiveType, MinVertexIndex, NumVertexIndices, PrimitiveCount, pIndexData, IndexDataFormat, pVertexStreamZeroData, VertexStreamZeroStride)) \
  X(HRESULT, ProcessVertices, (UINT SrcStartIndex, UINT DestIndex, UINT VertexCount, IDirect3DVertexBuffer8 *pDestBuffer, DWORD Flags), (SrcStartIndex, DestIndex, VertexCount, pDestBuffer, Flags)) \
  X(HRESULT, CreateVertexShader, (const DWORD *pDeclaration, const DWORD *pFunction, DWORD *pHandle, DWORD Usage), (pDeclaration, pFunction, pHandle, Usage)) \
  X(HRESULT, SetVertexShader, (DWORD Handle), (Handle)) \
  X(HRESULT, GetVertexShader, (DWORD *pHandle), (pHandle)) \
  X(HRESULT, DeleteVertexShader, (DWORD Handle), (Handle)) \
  X(HRESULT, SetVertexShaderConstant, (DWORD Register, const void *pConstantData, DWORD ConstantCount), (Register, pConstantData, ConstantCount)) \
  X(HRESULT, GetVertexShaderConstant, (DWORD Register, void *pConstantData, DWORD ConstantCount), (Register, pConstantData, ConstantCount)) \
  X(HRESULT, GetVertexShaderDeclaration, (DWORD Handle, void *pData, DWORD *pSizeOfData), (Handle, pData, pSizeOfData)) \
  X(HRESULT, GetVertexShaderFunction, (DWORD Handle, void *pData, DWORD *pSizeOfData), (Handle, pData, pSizeOfData)) \
  X(HRESULT, SetStreamSource, (UINT StreamNumber, IDirect3DVertexBuffer8 *pStreamData, UINT Stride), (StreamNumber, pStreamData, Stride)) \
  X(HRESULT, GetStreamSource, (UINT StreamNumber, IDirect3DVertexBuffer8 **ppStreamData, UINT *pStride), (StreamNumber, ppStreamData, pStride)) \
  X(HRESULT, SetIndices, (IDirect3DIndexBuffer8 *pIndexData, UINT BaseVertexIndex), (pIndexData, BaseVertexIndex)) \
  X(HRESULT, GetIndices, (IDirect3DIndexBuffer8 **ppIndexData, UINT *pBaseVertexIndex), (ppIndexData, pBaseVertexIndex)) \
  X(HRESULT, CreatePixelShader, (const DWORD *pFunction, DWORD *pHandle), (pFunction, pHandle)) \
  X(HRESULT, SetPixelShader, (DWORD Handle), (Handle)) \
  X(HRESULT, GetPixelShader, (DWORD *pHandle), (pHandle)) \
  X(HRESULT, DeletePixelShader, (DWORD Handle), (Handle)) \
  X(HRESULT, SetPixelShaderConstant, (DWORD Register, const void *pConstantData, DWORD ConstantCount), (Register, pConstantData, ConstantCount)) \
  X(HRESULT, GetPixelShaderConstant, (DWORD Register, void *pConstantData, DWORD ConstantCount), (Register, pConstantData, ConstantCount)) \
  X(HRESULT, GetPixelShaderFunction, (DWORD Handle, void *pData, DWORD *pSizeOfData), (Handle, pData, pSizeOfData)) \
  X(HRESULT, DrawRectPatch, (UINT Handle, const float *pNumSegs, const D3DRECTPATCH_INFO *pRectPatchInfo), (Handle, pNumSegs, pRectPatchInfo)) \
  X(HRESULT, DrawTriPatch, (UINT Handle, const float *pNumSegs, const D3DTRIPATCH_INFO *pTriPatchInfo), (Handle, pNumSegs, pTriPatchInfo)) \
  X(HRESULT, DeletePatch, (UINT Handle), (Handle))

// IDirect3DDevice8: pass-through only
#define GK_IDIRECT3DDEVICE8_FORWARDED(X) \
  X(HRESULT, TestCooperativeLevel, (), ()) \
  X(UINT, GetAvailableTextureMem, (), ()) \
  X(HRESULT, ResourceManagerDiscardBytes, (DWORD Bytes), (Bytes)) \
  X(HRESULT, GetDeviceCaps, (D3DCAPS8 *pCaps), (pCaps)) \
  X(HRESULT, GetDisplayMode, (D3DDISPLAYMODE *pMode), (pMode)) \
  X(HRESULT, GetCreationParameters, (D3DDEVICE_CREATION_PARAMETERS *pParameters), (pParameters)) \
  X(void, SetCursorPosition, (UINT XScreenSpace, UINT YScreenSpace, DWORD Flags), (XScreenSpace, YScreenSpace, Flags)) \
  X(BOOL, ShowCursor, (BOOL bShow), (bShow)) \
  X(HRESULT, CreateAdditionalSwapChain, (D3DPRESENT_PARAMETERS8 *pPresentationParameters, IDirect3DSwapChain8 **ppSwapChain), (pPresentationParameters, ppSwapChain)) \
  X(HRESULT, GetRasterStatus, (D3DRASTER_STATUS *pRasterStatus), (pRasterStatus)) \
  X(void, SetGammaRamp, (DWORD Flags, const D3DGAMMARAMP *pRamp), (Flags, pRamp)) \
  X(void, GetGammaRamp, (D3DGAMMARAMP *pRamp), (pRamp)) \
  X(HRESULT, CreateVolumeTexture, (UINT Width, UINT Height, UINT Depth, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DVolumeTexture8 **ppVolumeTexture), (Width, Height, Depth, Levels, Usage, Format, Pool, ppVolumeTexture)) \
  X(HRESULT, CreateCubeTexture, (UINT EdgeLength, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DCubeTexture8 **ppCubeTexture), (EdgeLength, Levels, Usage, Format, Pool, ppCubeTexture)) \
  X(HRESULT, GetTransform, (D3DTRANSFORMSTATETYPE State, D3DMATRIX *pMatrix), (State, pMatrix)) \
  X(HRESULT, MultiplyTransform, (D3DTRANSFORMSTATETYPE State, const D3DMATRIX *pMatrix), (State, pMatrix)) \
  X(HRESULT, GetViewport, (D3DVIEWPORT8 *pViewport), (pViewport)) \
  X(HRESULT, GetMaterial, (D3DMATERIAL8 *pMaterial), (pMaterial)) \
  X(HRESULT, GetLight, (DWORD Index, D3DLIGHT8 *pLight), (Index, pLight)) \
  X(HRESULT, GetLightEnable, (DWORD Index, BOOL *pEnable), (Index, pEnable)) \
  X(HRESULT, SetClipPlane, (DWORD Index, const float *pPlane), (Index, pPlane)) \
  X(HRESULT, GetClipPlane, (DWORD Index, float *pPlane), (Index, pPlane)) \
  X(HRESULT, GetRenderState, (D3DRENDERSTATETYPE State, DWORD *pValue), (State, pValue)) \
  X(HRESULT, SetClipStatus, (const D3DCLIPSTATUS8 *pClipStatus), (pClipStatus)) \
  X(HRESULT, GetClipStatus, (D3DCLIPSTATUS8 *pClipStatus), (pClipStatus)) \
  X(HRESULT, GetTextureStageState, (DWORD Stage, D3DTEXTURESTAGESTATETYPE Type, DWORD *pValue), (Stage, Type, pValue)) \
  X(HRESULT, ValidateDevice, (DWORD *pNumPasses), (pNumPasses)) \
  X(HRESULT, GetInfo, (DWORD DevInfoID, void *pDevInfoStruct, DWORD DevInfoStructSize), (DevInfoID, pDevInfoStruct, DevInfoStructSize)) \
  X(HRESULT, SetPaletteEntries, (UINT PaletteNumber, const PALETTEENTRY *pEntries), (PaletteNumber, pEntries)) \
  X(HRESULT, GetPaletteEntries, (UINT PaletteNumber, PALETTEENTRY *pEntries), (PaletteNumber, pEntries)) \
  X(HRESULT, SetCurrentTexturePalette, (UINT PaletteNumber), (PaletteNumber)) \
  X(HRESULT, GetCurrentTexturePalette, (UINT *PaletteNumber), (PaletteNumber)) \
  X(HRESULT, CreateVertexShader, (const DWORD *pDeclaration, const DWORD *pFunction, DWORD *pHandle, DWORD Usage), (pDeclaration, pFunction, pHandle, Usage)) \
  X(HRESULT, GetVertexShader, (DWORD *pHandle), (pHandle)) \
  X(HRESULT, DeleteVertexShader, (DWORD Handle), (Handle)) \
  X(HRESULT, SetVertexShaderConstant, (DWORD Register, const void *pConstantData, DWORD ConstantCount), (Register, pConstantData, ConstantCount)) \
  X(HRESULT, GetVertexShaderConstant, (DWORD Register, void *pConstantData, DWORD ConstantCount), (Register, pConstantData, ConstantCount)) \
  X(HRESULT, GetVertexShaderDeclaration, (DWORD Handle, void *pData, DWORD *pSizeOfData), (Handle, pData, pSizeOfData)) \
  X(HRESULT, GetVertexShaderFunction, (DWORD Handle, void *pData, DWORD *pSizeOfData), (Handle, pData, pSizeOfData)) \
  X(HRESULT, CreatePixelShader, (const DWORD *pFunction, DWORD *pHandle), (pFunction, pHandle)) \
  X(HRESULT, SetPixelShader, (DWORD Handle), (Handle)) \
  X(HRESULT, GetPixelShader, (DWORD *pHandle), (pHandle)) \
  X(HRESULT, DeletePixelShader, (DWORD Handle), (Handle)) \
  X(HRESULT, SetPixelShaderConstant, (DWORD Register, const void *pConstantData, DWORD ConstantCount), (Register, pConstantData, ConstantCount)) \
  X(HRESULT, GetPixelShaderConstant, (DWORD Register, void *pConstantData, DWORD ConstantCount), (Register, pConstantData, ConstantCount)) \
  X(HRESULT, GetPixelShaderFunction, (DWORD Handle, void *pData, DWORD *pSizeOfData), (Handle, pData, pSizeOfData)) \
  X(HRESULT, DrawRectPatch, (UINT Handle, const float *pNumSegs, const D3DRECTPATCH_INFO *pRectPatchInfo), (Handle, pNumSegs, pRectPatchInfo)) \
  X(HRESULT, DrawTriPatch, (UINT Handle, const float *pNumSegs, const D3DTRIPATCH_INFO *pTriPatchInfo), (Handle, pNumSegs, pTriPatchInfo)) \
  X(HRESULT, DeletePatch, (UINT Handle), (Handle))

// IDirect3DVertexBuffer8: all methods
#define GK_IDIRECT3DVERTEXBUFFER8_METHODS(X) \
  X(HRESULT, GetDevice, (IDirect3DDevice8 **ppDevice), (ppDevice)) \
  X(HRESULT, SetPrivateData, (REFGUID refguid, const void *pData, DWORD SizeOfData, DWORD Flags), (refguid, pData, SizeOfData, Flags)) \
  X(HRESULT, GetPrivateData, (REFGUID refguid, void *pData, DWORD *pSizeOfData), (refguid, pData, pSizeOfData)) \
  X(HRESULT, FreePrivateData, (REFGUID refguid), (refguid)) \
  X(DWORD, SetPriority, (DWORD PriorityNew), (PriorityNew)) \
  X(DWORD, GetPriority, (), ()) \
  X(void, PreLoad, (), ()) \
  X(D3DRESOURCETYPE, GetType, (), ()) \
  X(HRESULT, Lock, (UINT OffsetToLock, UINT SizeToLock, BYTE **ppbData, DWORD Flags), (OffsetToLock, SizeToLock, ppbData, Flags)) \
  X(HRESULT, Unlock, (), ()) \
  X(HRESULT, GetDesc, (D3DVERTEXBUFFER_DESC *pDesc), (pDesc))

// IDirect3DVertexBuffer8: pass-through only
#define GK_IDIRECT3DVERTEXBUFFER8_FORWARDED(X) \
  X(HRESULT, SetPrivateData, (REFGUID refguid, const void *pData, DWORD SizeOfData, DWORD Flags), (refguid, pData, SizeOfData, Flags)) \
  X(HRESULT, GetPrivateData, (REFGUID refguid, void *pData, DWORD *pSizeOfData), (refguid, pData, pSizeOfData)) \
  X(HRESULT, FreePrivateData, (REFGUID refguid), (refguid)) \
  X(DWORD, SetPriority, (DWORD PriorityNew), (PriorityNew)) \
  X(DWORD, GetPriority, (), ()) \
  X(void, PreLoad, (), ()) \
  X(D3DRESOURCETYPE, GetType, (), ()) \
  X(HRESULT, GetDesc, (D3DVERTEXBUFFER_DESC *pDesc), (pDesc))

// IDirect3DIndexBuffer8: all methods
#define GK_IDIRECT3DINDEXBUFFER8_METHODS(X) \
  X(HRESULT, GetDevice, (IDirect3DDevice8 **ppDevice), (ppDevice)) \
  X(HRESULT, SetPrivateData, (REFGUID refguid, const void *pData, DWORD SizeOfData, DWORD Flags), (refguid, pData, SizeOfData, Flags)) \
  X(HRESULT, GetPrivateData, (REFGUID refguid, void *pData, DWORD *pSizeOfData), (refguid, pData, pSizeOfData)) \
  X(HRESULT, FreePrivateData, (REFGUID refguid), (refguid)) \
  X(DWORD, SetPriority, (DWORD PriorityNew), (PriorityNew)) \
  X(DWORD, GetPriority, (), ()) \
  X(void, PreLoad, (), ()) \
  X(D3DRESOURCETYPE, GetType, (), ()) \
  X(HRESULT, Lock, (UINT OffsetToLock, UINT SizeToLock, BYTE **ppbData, DWORD Flags), (OffsetToLock, SizeToLock, ppbData, Flags)) \
  X(HRESULT, Unlock, (), ()) \
  X(HRESULT, GetDesc, (D3DINDEXBUFFER_DESC *pDesc), (pDesc))

// IDirect3DIndexBuffer8: pass-through only
#define GK_IDIRECT3DINDEXBUFFER8_FORWARDED(X) \
  X(HRESULT, SetPrivateData, (REFGUID refguid, const void *pData, DWORD SizeOfData, DWORD Flags), (refguid, pData, SizeOfData, Flags)) \
  X(HRESULT, GetPrivateData, (REFGUID refguid, void *pData, DWORD *pSizeOfData), (refguid, pData, pSizeOfData)) \
  X(HRESULT, FreePrivateData, (REFGUID refguid), (refguid)) \
  X(DWORD, SetPriority, (DWORD PriorityNew), (PriorityNew)) \
  X(DWORD, GetPriority, (), ()) \
  X(void, PreLoad, (), ()) \
  X(D3DRESOURCETYPE, GetType, (), ()) \
  X(HRESULT, GetDesc, (D3DINDEXBUFFER_DESC *pDesc), (pDesc))

// IDirect3DTexture8: all methods
#define GK_IDIRECT3DTEXTURE8_METHODS(X) \
  X(HRESULT, GetDevice, (IDirect3DDevice8 **ppDevice), (ppDevice)) \
  X(HRESULT, SetPrivateData, (REFGUID refguid, const void *pData, DWORD SizeOfData, DWORD Flags), (refguid, pData, SizeOfData, Flags)) \
  X(HRESULT, GetPrivateData, (REFGUID refguid, void *pData, DWORD *pSizeOfData), (refguid, pData, pSizeOfData)) \
  X(HRESULT, FreePrivateData, (REFGUID refguid), (refguid)) \
  X(DWORD, SetPriority, (DWORD PriorityNew), (PriorityNew)) \
  X(DWORD, GetPriority, (), ()) \
  X(void, PreLoad, (), ()) \
  X(D3DRESOURCETYPE, GetType, (), ()) \
  X(DWORD, SetLOD, (DWORD LODNew), (LODNew)) \
  X(DWORD, GetLOD, (), ()) \
  X(DWORD, GetLevelCount, (), ()) \
  X(HRESULT, GetLevelDesc, (UINT Level, D3DSURFACE_DESC8 *pDesc), (Level, pDesc)) \
  X(HRESULT, GetSurfaceLevel, (UINT Level, IDirect3DSurface8 **ppSurfaceLevel), (Level, ppSurfaceLevel)) \
  X(HRESULT, LockRect, (UINT Level, D3DLOCKED_RECT *pLockedRect, const RECT *pRect, DWORD Flags), (Level, pLockedRect, pRect, Flags)) \
  X(HRESULT, UnlockRect, (UINT Level), (Level)) \
  X(HRESULT, AddDirtyRect, (const RECT *pDirtyRect), (pDirtyRect))

// IDirect3DTexture8: pass-through only
#define GK_IDIRECT3DTEXTURE8_FORWARDED(X) \
  X(HRESULT, SetPrivateData, (REFGUID refguid, const void *pData, DWORD SizeOfData, DWORD Flags), (refguid, pData, SizeOfData, Flags)) \
  X(HRESULT, GetPrivateData, (REFGUID refguid, void *pData, DWORD *pSizeOfData), (refguid, pData, pSizeOfData)) \
  X(HRESULT, FreePrivateData, (REFGUID refguid), (refguid)) \
  X(DWORD, SetPriority, (DWORD PriorityNew), (PriorityNew)) \
  X(DWORD, GetPriority, (), ()) \
  X(void, PreLoad, (), ()) \
  X(D3DRESOURCETYPE, GetType, (), ()) \
  X(DWORD, SetLOD, (DWORD LODNew), (LODNew)) \
  X(DWORD, GetLOD, (), ()) \
  X(DWORD, GetLevelCount, (), ()) \
  X(HRESULT, GetLevelDesc, (UINT Level, D3DSURFACE_DESC8 *pDesc), (Level, pDesc)) \
  X(HRESULT, AddDirtyRect, (const RECT *pDirtyRect), (pDirtyRect))

// IDirect3DSurface8: all methods
#define GK_IDIRECT3DSURFACE8_METHODS(X) \
  X(HRESULT, GetDevice, (IDirect3DDevice8 **ppDevice), (ppDevice)) \
  X(HRESULT, SetPrivateData, (REFGUID refguid, const void *pData, DWORD SizeOfData, DWORD Flags), (refguid, pData, SizeOfData, Flags)) \
  X(HRESULT, GetPrivateData, (REFGUID refguid, void *pData, DWORD *pSizeOfData), (refguid, pData, pSizeOfData)) \
  X(HRESULT, FreePrivateData, (REFGUID refguid), (refguid)) \
  X(HRESULT, GetContainer, (REFIID riid, void **ppContainer), (riid, ppContainer)) \
  X(HRESULT, GetDesc, (D3DSURFACE_DESC8 *pDesc), (pDesc)) \
  X(HRESULT, LockRect, (D3DLOCKED_RECT *pLockedRect, const RECT *pRect, DWORD Flags), (pLockedRect, pRect, Flags)) \
  X(HRESULT, UnlockRect, (), ())

// IDirect3DSurface8: pass-through only
#define GK_IDIRECT3DSURFACE8_FORWARDED(X) \
  X(HRESULT, SetPrivateData, (REFGUID refguid, const void *pData, DWORD SizeOfData, DWORD Flags), (refguid, pData, SizeOfData, Flags)) \
  X(HRESULT, GetPrivateData, (REFGUID refguid, void *pData, DWORD *pSizeOfData), (refguid, pData, pSizeOfData)) \
  X(HRESULT, FreePrivateData, (REFGUID refguid), (refguid)) \
  X(HRESULT, GetDesc, (D3DSURFACE_DESC8 *pDesc), (pDesc))
