#!/usr/bin/env python3
"""Compile src/shaders/*.slang to SPIR-V and embed the result in a header.

Slang rather than GLSL, and it is worth saying why beyond taste: it is Khronos's own shading
language now, it ships in the Vulkan SDK, and it gives this project two things GLSL does not -
generics and interfaces for the übershader's stage ops, and one file per pass holding every
entry point, so a push constant block shared across stages cannot drift between two files.

Shaders are compiled OFFLINE and the generated header is checked in, so `d3d8.dll` depends on
no shader toolchain at runtime - the same reasoning that makes the renderer reach Vulkan through
volk rather than the loader's import library. GkPlus *is* `d3d8.dll`, and a missing build-time
tool must not stop the game launching. Nothing in CMake calls this; the header is the artifact.

Re-run after editing any shader:

    python3 src/gen-shaders.py

Output is `src/Shaders.gen.inc.h`, one `const uint32_t kXxxSpv[]` per entry point.
"""

import glob
import pathlib
import re
import subprocess
import sys

SHADER_DIR = pathlib.Path("src/shaders")
OUTPUT = pathlib.Path("src/Shaders.gen.inc.h")

# One SPIR-V module per entry point rather than one multi-entry module: VkPipelineShaderStage
# names an entry point, so either shape works, but separate modules keep the C++ side from
# having to know which names live in which blob.
#
# `-fvk-use-entrypoint-name` stops Slang renaming every entry to "main", which matters because
# the C++ passes the name through verbatim.
ENTRY_POINTS = [
    ("world.slang", "vertex_main", "vertex"),
    ("world.slang", "fragment_main", "fragment"),
]

SLANGC_ARGS = [
    "-target", "spirv",
    "-profile", "spirv_1_5",
    "-matrix-layout-row-major",
    "-fvk-use-entrypoint-name",
    "-O2",
]


def find_slangc():
    from shutil import which
    found = which("slangc")
    if found:
        return found
    candidates = sorted(glob.glob("C:/VulkanSDK/*/Bin/slangc.exe"))
    if candidates:
        return candidates[-1]
    sys.exit("slangc not found - install the Vulkan SDK or put slangc on PATH")


def symbol(entry):
    """vertex_main -> kVertexMainSpv"""
    return "k" + "".join(part.capitalize() for part in entry.split("_")) + "Spv"


def main():
    slangc = find_slangc()
    out = [
        "// Generated by src/gen-shaders.py from src/shaders/*.slang. Do not edit.",
        "//",
        "// SPIR-V is embedded rather than compiled at runtime so that d3d8.dll depends on no",
        "// shader toolchain. Re-run the generator after editing a shader.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
    ]

    for source_name, entry, stage in ENTRY_POINTS:
        source = SHADER_DIR / source_name
        if not source.exists():
            sys.exit("%s not found" % source)
        output = SHADER_DIR / ("%s.%s.spv" % (source.stem, entry))
        result = subprocess.run(
            [slangc, str(source), "-entry", entry, "-stage", stage] + SLANGC_ARGS +
            ["-o", str(output)],
            capture_output=True)
        if result.returncode != 0:
            sys.exit("%s:%s failed to compile:\n%s"
                     % (source_name, entry,
                        (result.stderr + result.stdout).decode("utf-8", "replace")))
        blob = output.read_bytes()
        output.unlink()
        if len(blob) % 4 != 0:
            sys.exit("%s:%s produced %d bytes, not a whole number of SPIR-V words"
                     % (source_name, entry, len(blob)))
        words = ["0x%08x" % int.from_bytes(blob[i:i + 4], "little")
                 for i in range(0, len(blob), 4)]
        out.append("// %s : %s (%s, %d words)"
                   % (source.as_posix(), entry, stage, len(words)))
        out.append("inline const uint32_t %s[] = {" % symbol(entry))
        for i in range(0, len(words), 8):
            out.append("    " + ", ".join(words[i:i + 8]) + ",")
        out.append("};")
        out.append("")
        print("%-22s %-16s %5d words" % (source_name, entry, len(words)))

    OUTPUT.write_text("\n".join(out), encoding="utf-8")
    print("wrote %s" % OUTPUT)


if __name__ == "__main__":
    main()
