#ifndef GUNLOK_MENU
#define GUNLOK_MENU(...)
#endif

GUNLOK_MENU(Main, 0)
GUNLOK_MENU(Options, 1)
GUNLOK_MENU(ScreenMode, 2)
GUNLOK_MENU(GfxCard, 3)
GUNLOK_MENU(Keyboard, 4)
GUNLOK_MENU(ChooseSinglePlayerLevel, 5)
GUNLOK_MENU(MouseControls, 6)
GUNLOK_MENU(SinglePlayer, 7)
GUNLOK_MENU(LoadSinglePlayerGame, 8)
GUNLOK_MENU(NewSinglePlayerGame, 9)
GUNLOK_MENU(Multiplayer, 10)
GUNLOK_MENU(JoinIPGame, 12)
GUNLOK_MENU(HostIPGame, 13)
GUNLOK_MENU(TrainingLevel, 21)
GUNLOK_MENU(Video, 22)
GUNLOK_MENU(Controls, 23)
GUNLOK_MENU(GraphicDetails, 24)
GUNLOK_MENU(Audio, 25)
GUNLOK_MENU(GamePreferences, 26)
GUNLOK_MENU(IPGame, 27)
GUNLOK_MENU(Camera, 28)
GUNLOK_MENU(Mines, 29)
GUNLOK_MENU(Character, 30)
GUNLOK_MENU(Gameplay, 31)
GUNLOK_MENU(ActivePause, 32)
GUNLOK_MENU(Recon, 33)
GUNLOK_MENU(Formations, 34)
GUNLOK_MENU(Music, 35)

#undef GUNLOK_MENU