// Generated by src/gen-shader-abi.py from src/shaders/*.slang. Do not edit.
//
// One `offsetof` per field and one `sizeof` per struct, derived from the SHADER's own
// declaration - so a C++ struct that drifts from the shader it feeds is a compile error
// naming the field. That is the link vulkan_renderer_notes.md 4.67 did not have: a
// permutation preserves the size, and the two hand-written asserts it did have pinned
// fields after the disturbance, so nothing failed until a float's bit pattern reached a
// bindless sampler index and took the device down (4.66).
//
// Included from VkDraw.cpp, inside its anonymous namespace - the one point where
// src/VkDraw.h, src/VertexFormat.h and that file's three push blocks are all in scope.
// recipe-hash: a9cc25a55f9d9af550c8bf75e4654da2e3aad969760d22732ffa704a843139f4
// source-hash: src/shaders/world.slang 21046e18a4b8bdb2897d477cbac688dd1c460f973550c0fcdd4b3d231ced695e
// source-hash: src/shaders/shadow.slang b325b3a5b737846cc8af68c3c9aa6a8ad7b67e01d1baa16d2196d8342fa9fa59
// source-hash: src/shaders/lightgrid.slang ff7a10915c25b2d2a2a2d60a06decb9fa459a327c1cfe0e04f1655221fc1fa8b
#pragma once

#include <cstddef>

// src/shaders/world.slang : struct GpuFrameData
static_assert(offsetof(GpuFrameData, map_lights) == 0,
              "GpuFrameData::map_lights moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, light_grid) == 8,
              "GpuFrameData::light_grid moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, light_indices) == 16,
              "GpuFrameData::light_indices moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, force_lod) == 24,
              "GpuFrameData::force_lod moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, bump_scale) == 28,
              "GpuFrameData::bump_scale moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, bump_diffuse) == 32,
              "GpuFrameData::bump_diffuse moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, specular_scale) == 36,
              "GpuFrameData::specular_scale moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, gloss_min) == 40,
              "GpuFrameData::gloss_min moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, gloss_max) == 44,
              "GpuFrameData::gloss_max moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, specular_from_diffuse) == 48,
              "GpuFrameData::specular_from_diffuse moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, chrome_scale) == 52,
              "GpuFrameData::chrome_scale moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, chrome_blur) == 56,
              "GpuFrameData::chrome_blur moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, chrome_texgen) == 60,
              "GpuFrameData::chrome_texgen moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, per_pixel_lighting) == 64,
              "GpuFrameData::per_pixel_lighting moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, map_light_gain) == 68,
              "GpuFrameData::map_light_gain moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, map_ambience) == 72,
              "GpuFrameData::map_ambience moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, map_light_count) == 76,
              "GpuFrameData::map_light_count moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, map_flags) == 80,
              "GpuFrameData::map_flags moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, shadow_texture) == 84,
              "GpuFrameData::shadow_texture moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, shadow_sampler) == 88,
              "GpuFrameData::shadow_sampler moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, shadow_strength) == 92,
              "GpuFrameData::shadow_strength moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, shadow_texel) == 96,
              "GpuFrameData::shadow_texel moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, shadow_z_near) == 100,
              "GpuFrameData::shadow_z_near moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, shadow_z_span) == 104,
              "GpuFrameData::shadow_z_span moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, shadow_cascades) == 108,
              "GpuFrameData::shadow_cascades moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, map_shadow_texture) == 112,
              "GpuFrameData::map_shadow_texture moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, map_shadow_sampler) == 116,
              "GpuFrameData::map_shadow_sampler moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, map_shadow_offset) == 120,
              "GpuFrameData::map_shadow_offset moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, dyn_shadow_texture) == 124,
              "GpuFrameData::dyn_shadow_texture moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, dyn_shadow_sampler) == 128,
              "GpuFrameData::dyn_shadow_sampler moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, dyn_shadow_offset) == 132,
              "GpuFrameData::dyn_shadow_offset moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, local_shadow_taps) == 136,
              "GpuFrameData::local_shadow_taps moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, tess_edge_pixels) == 140,
              "GpuFrameData::tess_edge_pixels moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, tess_max) == 144,
              "GpuFrameData::tess_max moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, tess_min) == 148,
              "GpuFrameData::tess_min moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, pn_strength) == 152,
              "GpuFrameData::pn_strength moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, pn_flat_threshold) == 156,
              "GpuFrameData::pn_flat_threshold moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, target_width) == 160,
              "GpuFrameData::target_width moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, target_height) == 164,
              "GpuFrameData::target_height moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, pn_max_offset) == 168,
              "GpuFrameData::pn_max_offset moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, light_flags) == 172,
              "GpuFrameData::light_flags moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, cascades) == 176,
              "GpuFrameData::cascades moved away from world.slang's GpuFrameData");
static_assert(offsetof(GpuFrameData, sun_matrix) == 240,
              "GpuFrameData::sun_matrix moved away from world.slang's GpuFrameData");
static_assert(sizeof(GpuFrameData) == 304,
              "GpuFrameData is not the size GpuFrameData declares");

// src/shaders/world.slang : struct GpuLight
static_assert(offsetof(GpuLight, position) == 0,
              "GpuLight::position moved away from world.slang's GpuLight");
static_assert(offsetof(GpuLight, direction) == 16,
              "GpuLight::direction moved away from world.slang's GpuLight");
static_assert(offsetof(GpuLight, diffuse) == 32,
              "GpuLight::diffuse moved away from world.slang's GpuLight");
static_assert(offsetof(GpuLight, specular) == 48,
              "GpuLight::specular moved away from world.slang's GpuLight");
static_assert(offsetof(GpuLight, ambient) == 64,
              "GpuLight::ambient moved away from world.slang's GpuLight");
static_assert(offsetof(GpuLight, attenuation) == 80,
              "GpuLight::attenuation moved away from world.slang's GpuLight");
static_assert(offsetof(GpuLight, spot) == 96,
              "GpuLight::spot moved away from world.slang's GpuLight");
static_assert(sizeof(GpuLight) == 112,
              "GpuLight is not the size GpuLight declares");

// src/shaders/world.slang : struct GpuDrawRecord
static_assert(offsetof(GpuDrawRecord, mvp) == 0,
              "GpuDrawRecord::mvp moved away from world.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, world) == 64,
              "GpuDrawRecord::world moved away from world.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, normal_transform) == 128,
              "GpuDrawRecord::normal_transform moved away from world.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, material_ambient) == 176,
              "GpuDrawRecord::material_ambient moved away from world.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, material_diffuse) == 192,
              "GpuDrawRecord::material_diffuse moved away from world.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, material_specular) == 208,
              "GpuDrawRecord::material_specular moved away from world.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, material_emissive) == 224,
              "GpuDrawRecord::material_emissive moved away from world.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, global_ambient) == 240,
              "GpuDrawRecord::global_ambient moved away from world.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, eye) == 256,
              "GpuDrawRecord::eye moved away from world.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, view_rotation) == 272,
              "GpuDrawRecord::view_rotation moved away from world.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, light_offset) == 320,
              "GpuDrawRecord::light_offset moved away from world.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, light_count) == 324,
              "GpuDrawRecord::light_count moved away from world.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, lighting) == 328,
              "GpuDrawRecord::lighting moved away from world.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, lit_colour) == 332,
              "GpuDrawRecord::lit_colour moved away from world.slang's GpuDrawRecord");
static_assert(sizeof(GpuDrawRecord) == 336,
              "GpuDrawRecord is not the size GpuDrawRecord declares");

// src/shaders/world.slang : struct GpuMaterial
static_assert(offsetof(GpuMaterial, stage0_texture) == 0,
              "GpuMaterial::stage0_texture moved away from world.slang's GpuMaterial");
static_assert(offsetof(GpuMaterial, stage0_sampler) == 4,
              "GpuMaterial::stage0_sampler moved away from world.slang's GpuMaterial");
static_assert(offsetof(GpuMaterial, stage0_color) == 8,
              "GpuMaterial::stage0_color moved away from world.slang's GpuMaterial");
static_assert(offsetof(GpuMaterial, stage0_alpha) == 12,
              "GpuMaterial::stage0_alpha moved away from world.slang's GpuMaterial");
static_assert(offsetof(GpuMaterial, stage1_texture) == 16,
              "GpuMaterial::stage1_texture moved away from world.slang's GpuMaterial");
static_assert(offsetof(GpuMaterial, stage1_sampler) == 20,
              "GpuMaterial::stage1_sampler moved away from world.slang's GpuMaterial");
static_assert(offsetof(GpuMaterial, stage1_color) == 24,
              "GpuMaterial::stage1_color moved away from world.slang's GpuMaterial");
static_assert(offsetof(GpuMaterial, stage1_alpha) == 28,
              "GpuMaterial::stage1_alpha moved away from world.slang's GpuMaterial");
static_assert(offsetof(GpuMaterial, stage_count) == 32,
              "GpuMaterial::stage_count moved away from world.slang's GpuMaterial");
static_assert(offsetof(GpuMaterial, flags) == 36,
              "GpuMaterial::flags moved away from world.slang's GpuMaterial");
static_assert(offsetof(GpuMaterial, shading) == 40,
              "GpuMaterial::shading moved away from world.slang's GpuMaterial");
static_assert(offsetof(GpuMaterial, tint) == 44,
              "GpuMaterial::tint moved away from world.slang's GpuMaterial");
static_assert(offsetof(GpuMaterial, lighting_texture) == 48,
              "GpuMaterial::lighting_texture moved away from world.slang's GpuMaterial");
static_assert(offsetof(GpuMaterial, chrome) == 52,
              "GpuMaterial::chrome moved away from world.slang's GpuMaterial");
static_assert(offsetof(GpuMaterial, pad1) == 56,
              "GpuMaterial::pad1 moved away from world.slang's GpuMaterial");
static_assert(offsetof(GpuMaterial, pad2) == 60,
              "GpuMaterial::pad2 moved away from world.slang's GpuMaterial");
static_assert(sizeof(GpuMaterial) == 64,
              "GpuMaterial is not the size GpuMaterial declares");

// src/shaders/world.slang : struct GpuMapLight
static_assert(offsetof(GpuMapLight, position) == 0,
              "GpuMapLight::position moved away from world.slang's GpuMapLight");
static_assert(offsetof(GpuMapLight, colour) == 16,
              "GpuMapLight::colour moved away from world.slang's GpuMapLight");
static_assert(offsetof(GpuMapLight, axis) == 32,
              "GpuMapLight::axis moved away from world.slang's GpuMapLight");
static_assert(sizeof(GpuMapLight) == 48,
              "GpuMapLight is not the size GpuMapLight declares");

// src/shaders/world.slang : struct Vertex
static_assert(offsetof(CanonicalVertex, pos) == 0,
              "CanonicalVertex::pos moved away from world.slang's Vertex");
static_assert(offsetof(CanonicalVertex, normal) == 16,
              "CanonicalVertex::normal moved away from world.slang's Vertex");
static_assert(offsetof(CanonicalVertex, uv0) == 32,
              "CanonicalVertex::uv0 moved away from world.slang's Vertex");
static_assert(sizeof(CanonicalVertex) == 48,
              "CanonicalVertex is not the size Vertex declares");

// src/shaders/world.slang : struct Push
static_assert(offsetof(PushConstants, vertices) == 0,
              "PushConstants::vertices moved away from world.slang's Push");
static_assert(offsetof(PushConstants, draws) == 8,
              "PushConstants::draws moved away from world.slang's Push");
static_assert(offsetof(PushConstants, lights) == 16,
              "PushConstants::lights moved away from world.slang's Push");
static_assert(offsetof(PushConstants, materials) == 24,
              "PushConstants::materials moved away from world.slang's Push");
static_assert(offsetof(PushConstants, frame) == 32,
              "PushConstants::frame moved away from world.slang's Push");
static_assert(offsetof(PushConstants, record) == 40,
              "PushConstants::record moved away from world.slang's Push");
static_assert(offsetof(PushConstants, material) == 44,
              "PushConstants::material moved away from world.slang's Push");
static_assert(offsetof(PushConstants, base_vertex) == 48,
              "PushConstants::base_vertex moved away from world.slang's Push");
static_assert(offsetof(PushConstants, pad0) == 52,
              "PushConstants::pad0 moved away from world.slang's Push");
static_assert(sizeof(PushConstants) == 56,
              "PushConstants is not the size Push declares");

// src/shaders/shadow.slang : struct Vertex
static_assert(offsetof(CanonicalVertex, pos) == 0,
              "CanonicalVertex::pos moved away from shadow.slang's Vertex");
static_assert(offsetof(CanonicalVertex, normal) == 16,
              "CanonicalVertex::normal moved away from shadow.slang's Vertex");
static_assert(offsetof(CanonicalVertex, uv0) == 32,
              "CanonicalVertex::uv0 moved away from shadow.slang's Vertex");
static_assert(sizeof(CanonicalVertex) == 48,
              "CanonicalVertex is not the size Vertex declares");

// src/shaders/shadow.slang : struct GpuDrawRecord
static_assert(offsetof(GpuDrawRecord, mvp) == 0,
              "GpuDrawRecord::mvp moved away from shadow.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, world) == 64,
              "GpuDrawRecord::world moved away from shadow.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, normal_transform) == 128,
              "GpuDrawRecord::normal_transform moved away from shadow.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, material_ambient) == 176,
              "GpuDrawRecord::material_ambient moved away from shadow.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, material_diffuse) == 192,
              "GpuDrawRecord::material_diffuse moved away from shadow.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, material_specular) == 208,
              "GpuDrawRecord::material_specular moved away from shadow.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, material_emissive) == 224,
              "GpuDrawRecord::material_emissive moved away from shadow.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, global_ambient) == 240,
              "GpuDrawRecord::global_ambient moved away from shadow.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, eye) == 256,
              "GpuDrawRecord::eye moved away from shadow.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, view_rotation) == 272,
              "GpuDrawRecord::view_rotation moved away from shadow.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, light_offset) == 320,
              "GpuDrawRecord::light_offset moved away from shadow.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, light_count) == 324,
              "GpuDrawRecord::light_count moved away from shadow.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, lighting) == 328,
              "GpuDrawRecord::lighting moved away from shadow.slang's GpuDrawRecord");
static_assert(offsetof(GpuDrawRecord, lit_colour) == 332,
              "GpuDrawRecord::lit_colour moved away from shadow.slang's GpuDrawRecord");
static_assert(sizeof(GpuDrawRecord) == 336,
              "GpuDrawRecord is not the size GpuDrawRecord declares");

// src/shaders/shadow.slang : struct ShadowPush
static_assert(offsetof(ShadowPushConstants, vertices) == 0,
              "ShadowPushConstants::vertices moved away from shadow.slang's ShadowPush");
static_assert(offsetof(ShadowPushConstants, draws) == 8,
              "ShadowPushConstants::draws moved away from shadow.slang's ShadowPush");
static_assert(offsetof(ShadowPushConstants, params) == 16,
              "ShadowPushConstants::params moved away from shadow.slang's ShadowPush");
static_assert(offsetof(ShadowPushConstants, record) == 24,
              "ShadowPushConstants::record moved away from shadow.slang's ShadowPush");
static_assert(offsetof(ShadowPushConstants, base_vertex) == 28,
              "ShadowPushConstants::base_vertex moved away from shadow.slang's ShadowPush");
static_assert(offsetof(ShadowPushConstants, light_matrix) == 32,
              "ShadowPushConstants::light_matrix moved away from shadow.slang's ShadowPush");
static_assert(offsetof(ShadowPushConstants, pn_strength) == 96,
              "ShadowPushConstants::pn_strength moved away from shadow.slang's ShadowPush");
static_assert(offsetof(ShadowPushConstants, pn_flat_threshold) == 100,
              "ShadowPushConstants::pn_flat_threshold moved away from shadow.slang's ShadowPush");
static_assert(offsetof(ShadowPushConstants, pn_max_offset) == 104,
              "ShadowPushConstants::pn_max_offset moved away from shadow.slang's ShadowPush");
static_assert(offsetof(ShadowPushConstants, tess_factor) == 108,
              "ShadowPushConstants::tess_factor moved away from shadow.slang's ShadowPush");
static_assert(sizeof(ShadowPushConstants) == 112,
              "ShadowPushConstants is not the size ShadowPush declares");

// src/shaders/lightgrid.slang : struct GpuMapLight
static_assert(offsetof(GpuMapLight, position) == 0,
              "GpuMapLight::position moved away from lightgrid.slang's GpuMapLight");
static_assert(offsetof(GpuMapLight, colour) == 16,
              "GpuMapLight::colour moved away from lightgrid.slang's GpuMapLight");
static_assert(offsetof(GpuMapLight, axis) == 32,
              "GpuMapLight::axis moved away from lightgrid.slang's GpuMapLight");
static_assert(sizeof(GpuMapLight) == 48,
              "GpuMapLight is not the size GpuMapLight declares");

// src/shaders/lightgrid.slang : struct GridPush
static_assert(offsetof(LightGridPush, grid_min) == 0,
              "LightGridPush::grid_min moved away from lightgrid.slang's GridPush");
static_assert(offsetof(LightGridPush, cell_size) == 16,
              "LightGridPush::cell_size moved away from lightgrid.slang's GridPush");
static_assert(offsetof(LightGridPush, dims) == 32,
              "LightGridPush::dims moved away from lightgrid.slang's GridPush");
static_assert(offsetof(LightGridPush, index_capacity) == 48,
              "LightGridPush::index_capacity moved away from lightgrid.slang's GridPush");
static_assert(offsetof(LightGridPush, pad0) == 52,
              "LightGridPush::pad0 moved away from lightgrid.slang's GridPush");
static_assert(offsetof(LightGridPush, pad1) == 56,
              "LightGridPush::pad1 moved away from lightgrid.slang's GridPush");
static_assert(offsetof(LightGridPush, pad2) == 60,
              "LightGridPush::pad2 moved away from lightgrid.slang's GridPush");
static_assert(sizeof(LightGridPush) == 64,
              "LightGridPush is not the size GridPush declares");

// Constants declared on both sides
static_assert(kMaxShadowCascades == 4,
              "kMaxShadowCascades disagrees with world.slang's kMaxShadowCascades");
static_assert(kMapShadowFace == 64.0,
              "kMapShadowFace disagrees with world.slang's kMapShadowFace");
static_assert(kMapShadowTilesPerRow == 64.0,
              "kMapShadowTilesPerRow disagrees with world.slang's kMapShadowTilesPerRow");
static_assert(kDynShadowFace == 256.0,
              "kDynShadowFace disagrees with world.slang's kDynShadowFace");
static_assert(kDynShadowTilesPerRow == 16.0,
              "kDynShadowTilesPerRow disagrees with world.slang's kDynShadowTilesPerRow");
static_assert(kNoTexture == 0xffffffff,
              "kNoTexture disagrees with world.slang's kNoTexture");
